#
# Jerome's Room
#

homeassistant:
  customize:
    climate.bedroom_main2_east_thermostat:
      min_temp: 8
      max_temp: 25

group:
  # floorplan
  bedroom_main2_compact_ui:
    name: "Olga's Bedroom"
    entities:
    - input_select.bedroom_main2_mode
    - climate.bedroom_main2_thermostat
    - group.bedroom_main2_lights

  bedroom_main2_setpoints:
    entities:
    - climate.bedroom_main2_east_thermostat

  bedroom_main2_lights:


scene:
  - name: bedroom_main2_off
    entities:
      group.bedroom_main2_lights:
        state: off
      switch.bedroom_main2_appliances:
        state: off

  - name: bedroom_main2_sleep
    entities:
      group.bedroom_main2_lights:
        state: off

  - name: bedroom_main2_cosy
    entities:
      group.bedroom_main2_lights:
        state: on

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
