group:
  g_bedroom_main2_settings_ui:
    name: Settings
    icon: mdi:settings
    entities:
      - input_number.bedroom_main2_temperature_off
      - input_number.bedroom_main2_temperature_cosy
      - input_number.bedroom_main2_temperature_sleep
