#
# Outside
#

homeassistant:
  customize:
    # FIXME: media-control card ignores 'name' settings
    media_player.outside_amplifier:
      friendly_name: Outside Amplifier


media_player:
  - name: Outside Amplifier
    platform: onkyo
    host: utility-amp
    sources:
      #dvd: 'BD/DVD'
      video1: 'Media' # STB/DVR
      #video2: 'CBL/SAT' # Cable/SAT
      #video3: 'Game'
      #video6: 'PC' # PC
      #aux1: 'Ext Aux'
      cd: 'Kitchen Media'
      phono: 'Aux'
      fm: 'FM' # -> needs onkyo fix
      am: 'AM' # -> needs onkyo fix
      network: 'Network'
      usb: 'USB'

