homeassistant:
  customize:
    climate.kitchen_thermostat:
      friendly_name: "Kitchen Heating"
    sensor.kitchen_mean_temperature:
      friendly_name: "Kitchen"
      icon: mdi:thermometer
      unit_of_measurement: "\xB0C"

group:
  g_debug_kitchen_heating:
    entities:
      - climate.kitchen_thermostat
      - climate.kitchen_west_thermostat
      - switch.kitchen_demand

  # Non-UI group which forwards setpoint updates
  #  Name is mapped from climate.foo_thermostat -> group.g_foo_thermostat
  g_kitchen_thermostat:
    entities:
      - climate.kitchen_west_thermostat

climate:
  - name: kitchen_thermostat
    platform: generic_thermostat
    heater: switch.kitchen_demand
    target_sensor: sensor.kitchen_mean_temperature
    max_temp: 25
    min_temp: 5
    target_temp: 10.0

switch:
  - name: kitchen_demand
    platform: mqtt
    command_topic: ha/kitchen/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

sensor:
  - name: kitchen_current_temperature
    platform: mqtt
    state_topic: 'ha/kitchen_west/49/1/1'
    value_template: '{{ value_json.value }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: kitchen_mean_temperature
    platform: min_max
    type: max  # minimize occasional 0 readings. Replace with median?
    entity_ids:
      - sensor.kitchen_current_temperature

  - platform: template
    sensors:
      kitchen_setpoint:
        value_template: "{{ states.climate.kitchen_thermostat.attributes.temperature }}"
        unit_of_measurement: "\xB0C"
