- alias: "Kitchen Cosy Time"
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.kitchen_mode
        option: "Cosy"

- alias: "Kitchen Off Time"
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.kitchen_mode
        option: "Off"
