#
# Kitchen
#

homeassistant:
  customize:
    climate.kitchen_west_mode:
      min_temp: 5
      max_temp: 25

group:
  # floorplan
  kitchen_compact_ui:
    name: Kitchen
    icon: mdi:stove
    entities:
      - input_select.kitchen_mode
      - climate.kitchen_thermostat
      - binary_sensor.washing_machine
      - group.kitchen_lights
      - group.kitchen_multizone_audio_players

  kitchen_setpoints:
    name: Kitchen Setpoints
    entities:
      - climate.kitchen_west_mode

  kitchen_lights:
    name: Kitchen Lights

scene:
  - name: kitchen_off
    entities:
      group.kitchen_lights:
        state: off
      media_player.kitchen_speaker:
        state: paused
      group.kitchen_multizone_audio_players:
        state: paused
      ## Leave it on for now
      #media_player.kitchen_amplifier:
      #  state: off

  - name: kitchen_cosy
    entities:
      group.kitchen_lights:
        state: on
        brightness_pct: 50
      media_player.outside_amplifier_zone_2:
        state: on

  - name: kitchen_bright
    entities:
      group.kitchen_lights:
        state: on
        brightness_pct: 100
      media_player.outside_amplifier_zone_2:
        state: on

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
