#
# Kitchen
#

homeassistant:
  customize:
    climate.kitchen_west_mode:
      min_temp: 5
      max_temp: 25

    sensor.kitchen_west_air_temperature:
      friendly_name: Kitchen
    sensor.kitchen_battery_level:
      friendly_name: Kitchen Battery
      icon: mdi:battery

    # FIXME: media-control card ignores 'name' settings
    media_player.outside_amplifier_zone_2:
      friendly_name: Kitchen Amplifier

group:
  # floorplan
  kitchen_compact_ui:
    name: Kitchen
    icon: mdi:stove
    entities:
    - input_select.kitchen_mode
    - climate.kitchen_thermostat
    - binary_sensor.washing_machine
    - group.kitchen_lights

  kitchen_setpoints:
    name: Kitchen Setpoints
    entities:
    - climate.kitchen_west_mode

  kitchen_lights:
    name: Kitchen Lights

  kitchen_media_players:
    entities:
    - media_player.kitchen_speaker
    - media_player.outside_amplifier_zone_2

scene:
  - name: kitchen_off
    entities:
      group.kitchen_lights:
        state: off
      media_player.kitchen_speaker:
        state: paused
      ## Leave it on for now
      #media_player.kitchen_amplifier:
      #  state: off
      #media_player.snapcast_client_kitchen_2:
      #  state: on
      #  is_volume_muted: true

  - name: kitchen_cosy
    entities:
      group.kitchen_lights:
        state: on
        brightness_pct: 50
      media_player.outside_amplifier_zone_2:
        state: on

  - name: kitchen_bright
    entities:
      group.kitchen_lights:
        state: on
        brightness_pct: 100
      media_player.outside_amplifier_zone_2:
        state: on

cast:
  media_player:
    - host: kitchen-google-home
      # name: kitchen_speaker

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
