- platform: template
  sensors:
    kitchen_battery:
      value_template: >
        {% if states.zwave.kitchen %}
          {{ states.zwave.kitchen.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
