homeassistant:
  # Name of the location where Home Assistant is running
  name: WB
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 55
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

# View all events in a logbook
logbook: !include logbook.yaml

# Customize database
recorder:
  db_url: !secret db_url
  purge_days: 30

# Checks for available updates
updater:

# Enables the frontend
frontend:

# Track the sun
sun:

http:
  api_password: !secret api_password
#  base_url: !secret base_url

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1

#zwave:
#  usb_path: /dev/ttyUSB21
#  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config
#  polling_interval: 60000
#  device_config: !include zwave_device_config.yaml

#rfxtrx:
#  device: /dev/ttyUSB22
#  debug: False


#device_tracker: !include device_tracker.yaml

#ifttt:
#  key: !secret ifttt_key
#
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

tado:
  username: !secret tado_username
  password: !secret tado_password

#emulated_hue: !include emulated_hue.yaml
#
notify: !include_dir_merge_list notify
tts: !include tts.yaml

scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automation

group: !include groups.yaml

media_player: !include_dir_merge_list media_players
light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list thermostats
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
script: !include_dir_merge_named scripts
