homeassistant:
  # Name of the location where Home Assistant is running
  name: WB
  # Location required to calculate the time the sun rises and sets
  latitude: 52.23492
  longitude: -0.04496
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize:
      device_tracker.mark_phone:
        entity_picture: static/wb-icons/wb_mark.png
        friendly_name: "Mark's Phone"
      device_tracker.anne_phone:
        entity_picture: static/wb-icons/wb_anne.png
      device_tracker.jerome_phone:
        entity_picture: static/wb-icons/wb_jerome.png
      device_tracker.ros_phone:
        entity_picture: static/wb-icons/wb_ros.png
      device_tracker.thomas_phone:
        entity_picture: static/wb-icons/wb_thomas.png
      device_tracker.liane_phone:
        entity_picture: static/wb-icons/wb_liane.png


# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Track the sun
sun:

http:
  api_password: ***REMOVED***

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1

zwave:
  usb_path: /dev/ttyUSB21
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.0b9-py3.4-linux-armv7l.egg/config
  polling_interval: 60000

rfxtrx:
  device: /dev/ttyUSB22
  debug: False

device_tracker:
- platform: snmp
  host: 192.168.7.1
  community: public
  baseoid: 1.3.6.1.2.1.4.22.1.2
  track_new_devices: yes
  interval_seconds: 30
  consider_home: 180

- platform: owntracks
  max_gps_accuracy: 200

- platform: nmap_tracker
  hosts: 192.168.7.7-250
#  home_interval: 30
  track_new_devices: yes
# consider_home will be the number of seconds to wait till marking someone as not home after not being seen on scans.
# 900 seconds = 15 minutes
  consider_home: 1800

ifttt:
  key: ***REMOVED***

########## AUTOGENERATED ############
#

