homeassistant:
  # Name of the location where Home Assistant is running
  name: WB
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 55
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml
  packages:
    package_aeotec_multisensor: !include packages/aeotec_multisensor.yaml
    package_camera0: !include packages/dahua-cameras.yaml
    package_hottub: !include packages/hottub.yaml
    package_washing_machine: !include packages/washing-machine.yaml
    package_stream_radio: !include packages/stream-radio.yaml
    package_oil_monitor: !include packages/myolive.yaml

    package_study: !include packages/study/package.yaml
    package_study_heating: !include packages/study/heating-on-demand.yaml

    package_kitchen: !include packages/kitchen/package.yaml
    package_kitchen_heating: !include packages/kitchen/heating-on-demand.yaml

    package_hall: !include packages/hall/package.yaml
    package_hall_heating: !include packages/hall/heating-on-demand.yaml
    package_annex_hall_heating: !include packages/hall/annex-hall-heating-on-demand.yaml

    package_lounge: !include packages/lounge/package.yaml
    package_lounge_heating: !include packages/lounge/heating-on-demand.yaml

    package_library: !include packages/library/package.yaml
    package_library_heating: !include packages/library/heating-on-demand.yaml

    package_ballroom: !include packages/ballroom/package.yaml
    package_ballroom_heating: !include packages/ballroom/heating-on-demand.yaml

    package_armoury: !include packages/armoury/package.yaml
    package_guest_room: !include packages/guest_room/package.yaml

    package_bedroom_mark: !include packages/bedroom-mark/package.yaml
    package_bedroom_mark_heating: !include packages/bedroom-mark/heating-on-demand.yaml

    package_bedroom_jerome: !include packages/bedroom-jerome/package.yaml
    package_bedroom_jerome_heating: !include packages/bedroom-jerome/heating-on-demand.yaml

    package_bedroom_ros: !include packages/bedroom-ros/package.yaml
    package_bedroom_ros_heating: !include packages/bedroom-ros/heating-on-demand.yaml

    #package_room: !include packages/room/package.yaml

    package_lounge_media_dimming: !include packages/lounge-media-dimming.yaml
    package_ballroom_media_dimming: !include packages/ballroom-media-dimming.yaml
    package_bedroom_mark_media_dimming: !include packages/bedroom-mark-media-dimming.yaml

    package_modem_scraper: !include packages/modem_scraper.yaml

config:
discovery:

zone: !include zone.yaml

# Deps: camera
ffmpeg:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

# View all events in a logbook
logbook: !include logbook.yaml

# Customize database
recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 30

influxdb: !include influxdb.yaml


# Checks for available updates
updater:

# Enables the frontend
frontend:

map:

# Track the sun
sun:

http:
  api_password: !secret api_password
#  base_url: !secret base_url

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1

zwave:
  usb_path: /dev/ttyUSB21
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config
  polling_interval: 60000
  new_entity_ids: true
  device_config: !include zwave_device_config.yaml

rfxtrx:
  device: /dev/ttyUSB22
  debug: False

device_tracker: !include device_tracker.yaml

#ifttt:
#  key: !secret ifttt_key
#
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

tado:
  username: !secret tado_username
  password: !secret tado_password

emulated_hue: !include emulated_hue.yaml

notify: !include_dir_merge_list notify
ios:
tts: !include tts.yaml

scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automation

group: !include groups.yaml

media_player: !include_dir_merge_list media_players
light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list thermostats
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
script: !include_dir_merge_named scripts

