homeassistant:
  # Name of the location where Home Assistant is running
  name: WB
  # Location required to calculate the time the sun rises and sets
  latitude: 52.23492
  longitude: -0.04496
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize:
      device_tracker.mark_phone:
        entity_picture: /local/wb-icons/wb_mark.png
        friendly_name: "Mark's Phone"
      device_tracker.anne_phone:
        entity_picture: /local/wb-icons/wb_anne.png
      device_tracker.jerome_phone:
        entity_picture: /local/wb-icons/wb_jerome.png
      device_tracker.ros_phone:
        entity_picture: /local/wb-icons/wb_ros.png
      device_tracker.thomas_phone:
        entity_picture: /local/wb-icons/wb_thomas.png
      device_tracker.liane_phone:
        entity_picture: /local/wb-icons/wb_liane.png
      light.__level_41:
        friendly_name: Ballroom North
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_13:
        friendly_name: Hall West Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_14:
        friendly_name: Study East Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_15:
        friendly_name: Study West Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_24:
        friendly_name: Hall East Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_25:
        friendly_name: Library Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_29:
        friendly_name: Mark's Bedroom Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_30:
        friendly_name: Lounge East Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_33:
        friendly_name: Ballroom East Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_34:
        friendly_name: Kitchen Setpoint
      light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_43:
        friendly_name: Hall Annex Setpoint
      light.fibaro_system_fgd212_dimmer_2_level_39:
        friendly_name: Mark's Bedroom Overhead

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Track the sun
sun:

http:
  api_password: ***REMOVED***

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1

zwave:
  usb_path: /dev/ttyUSB21
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.0b9-py3.4-linux-armv7l.egg/config
  polling_interval: 60000

rfxtrx:
  device: /dev/ttyUSB22
  debug: False

device_tracker:
- platform: snmp
  host: 192.168.7.1
  community: public
  baseoid: 1.3.6.1.2.1.4.22.1.2
  track_new_devices: yes
  interval_seconds: 30
  consider_home: 180

- platform: owntracks
  max_gps_accuracy: 200

#- platform: nmap_tracker
#  hosts: 192.168.7.7-250
#  home_interval: 30
#  track_new_devices: yes
# consider_home will be the number of seconds to wait till marking someone as not home after not being seen on scans.
# 900 seconds = 15 minutes
#  consider_home: 1800

ifttt:
  key: ***REMOVED***

########## AUTOGENERATED ############
#

group:
  annex_heating:
    entities:
    - thermostat.horstmann_scsc17_thermostat_thermostat_mode_50
    - sensor.horstmann_scsc17_thermostat_thermostat_temperature_50
    - switch.horstmann_scsc17_thermostat_switch_50
    - switch.horstmann_unknown_type0003_id0001_switch_45
    - thermostat.horstmann_unknown_type0003_id0001_mode_45
    name: Annex Heating
    view: false
  ballroom:
    entities:
    - media_player.ballroom
    - group.ballroom_lights
    - group.ballroom_heating
    - group.ballroom_scenes
    icon: mdi:projector
    name: Ballroom
    view: true
  ballroom_heating:
    entities:
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_33
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_33
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_33
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_33
    name: Ballroom Heating
    view: false
  ballroom_lights:
    entities:
    - light.__level_41
    name: Ballroom Lights
    view: false
  ballroom_scenes:
    entities:
    - scene.ballroom_off
    - scene.ballroom_party
    - scene.ballroom_movie
    - scene.ballroom_bright
    name: Ballroom Scenes
    view: false
  bedroommark:
    entities:
    - switch.marks_bedroom_amp
    - media_player.marks_bedroom
    - group.marks_bedroom_lights
    - group.marks_bedroom_heating
    - group.marks_bedroom_scenes
    icon: mdi:hotel
    name: Mark's Bedroom
    view: true
  hall:
    entities:
    - group.hall_lights
    - group.hall_heating
    - group.hall_scenes
    - group.main_heating
    - group.annex_heating
    icon: mdi:fullscreen-exit
    name: Hall
    view: true
  hall_heating:
    entities:
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_13
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_13
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_13
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_13
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_24
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_24
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_24
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_24
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_43
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_43
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_43
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_43
    name: Hall Heating
    view: false
  hall_lights:
    name: Hall Lights
    view: false
  hall_scenes:
    name: Hall Scenes
    view: false
  kitchen:
    entities:
    - media_player.kitchen
    - group.kitchen_lights
    - group.kitchen_heating
    - group.kitchen_scenes
    icon: mdi:stove
    name: Kitchen
    view: true
  kitchen_heating:
    entities:
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_34
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_34
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_34
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_34
    name: Kitchen Heating
    view: false
  kitchen_lights:
    name: Kitchen Lights
    view: false
  kitchen_scenes:
    entities:
    - scene.kitchen_off
    - scene.kitchen_cosy
    - scene.kitchen_bright
    name: Kitchen Scenes
    view: false
  library:
    entities:
    - media_player.library
    - group.library_lights
    - group.library_heating
    - group.library_scenes
    icon: mdi:library
    name: Library
    view: true
  library_heating:
    entities:
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_25
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_25
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_25
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_25
    name: Library Heating
    view: false
  library_lights:
    name: Library Lights
    view: false
  library_scenes:
    entities:
    - scene.library_off
    - scene.library_chat
    - scene.library_read
    name: Library Scenes
    view: false
  lounge:
    entities:
    - media_player.lounge
    - group.lounge_lights
    - group.lounge_heating
    - group.lounge_scenes
    icon: mdi:sofa
    name: Lounge
    view: true
  lounge_heating:
    entities:
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_30
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_30
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_30
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_30
    name: Lounge Heating
    view: false
  lounge_lights:
    entities:
    - light.159947921
    - light.159782931
    - light.159782932
    name: Lounge Lights
    view: false
  lounge_scenes:
    entities:
    - scene.lounge_off
    - scene.lounge_cosy
    - scene.lounge_movie
    - scene.lounge_bright
    name: Lounge Scenes
    view: false
  main_heating:
    entities:
    - thermostat.horstmann_scsc17_thermostat_thermostat_mode_35
    - sensor.horstmann_scsc17_thermostat_thermostat_temperature_35
    - switch.horstmann_scsc17_thermostat_switch_35
    - switch.horstmann_unknown_type0003_id0002_switch_36
    - thermostat.horstmann_unknown_type0003_id0002_mode_36
    - switch.horstmann_unknown_type0003_id0002_switch_36_2
    - thermostat.horstmann_unknown_type0003_id0002_mode_36_2
    name: Main Heating
    view: false
  marks_bedroom_heating:
    entities:
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_29
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_29
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_29
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_29
    name: Mark's Bedroom Heating
    view: false
  marks_bedroom_lights:
    entities:
    - light.fibaro_system_fgd212_dimmer_2_level_39
    name: Mark's Bedroom Lights
    view: false
  marks_bedroom_scenes:
    entities:
    - scene.marks_bedroom_off
    - scene.marks_bedroom_sleep
    - scene.marks_bedroom_play
    name: Mark's Bedroom Scenes
    view: false
  people:
    entities:
    - device_tracker.mark_phone
    - device_tracker.anne_phone
    - device_tracker.jerome_phone
    - device_tracker.ros_phone
    - device_tracker.thomas_phone
    name: Who's In?
    view: false
  study:
    entities:
    - media_player.study
    - group.study_lights
    - group.study_heating
    - group.study_scenes
    icon: mdi:printer
    name: Study
    view: true
  study_heating:
    entities:
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_15
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_15
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_15
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_15
    - thermostat.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_mode_14
    - sensor.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_temperature_14
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_level_14
    - light.eurotronic_eur_stellaz_wall_radiator_thermostat_valve_control_step_size_14
    name: Study Heating
    view: false
  study_lights:
    name: Study Lights
    view: false
  study_scenes:
    entities:
    - scene.study_off
    - scene.study_work
    - scene.study_relax
    name: Study Scenes
    view: false

media_player:
- name: Study
  platform: kodi
  url: http://study/jsonrpc
- name: Lounge
  platform: kodi
  url: http://lounge/jsonrpc
- name: Mark's Bedroom
  password: ***REMOVED***
  platform: kodi
  url: http://bedroom-mark/jsonrpc
  username: gnome
- name: Kitchen
  platform: kodi
  url: http://kitchen:8080/jsonrpc
- name: Ballroom
  platform: kodi
  url: http://ballroom/jsonrpc
- name: Library
  platform: kodi
  url: http://library/jsonrpc
scene:
- entities: {}
  name: Study Off
- entities: {}
  name: Study Work
- entities: {}
  name: Study Relax
- entities:
    light.159782931:
      state: false
    light.159782932:
      state: false
    light.159947921:
      state: false
  name: Lounge Off
- entities:
    light.159782931:
      state: false
    light.159782932:
      state: false
    light.159947921:
      state: false
  name: Lounge Cosy
- entities:
    light.159782931:
      state: false
    light.159782932:
      state: false
    light.159947921:
      state: false
  name: Lounge Movie
- entities:
    light.159782931:
      state: false
    light.159782932:
      state: false
    light.159947921:
      state: false
  name: Lounge Bright
- entities:
    light.fibaro_system_fgd212_dimmer_2_level_39:
      state: false
  name: Mark's Bedroom Off
- entities:
    light.fibaro_system_fgd212_dimmer_2_level_39:
      state: false
  name: Mark's Bedroom Sleep
- entities:
    light.fibaro_system_fgd212_dimmer_2_level_39:
      state: false
  name: Mark's Bedroom Play
- entities: {}
  name: Kitchen Off
- entities: {}
  name: Kitchen Cosy
- entities: {}
  name: Kitchen Bright
- entities:
    light.__level_41:
      state: false
  name: Ballroom Off
- entities:
    light.__level_41:
      state: false
  name: Ballroom Party
- entities:
    light.__level_41:
      state: false
  name: Ballroom Movie
- entities:
    light.__level_41:
      state: false
  name: Ballroom Bright
- entities: {}
  name: Library Off
- entities: {}
  name: Library Chat
- entities: {}
  name: Library Read
sensor: []
switch:
- command_topic: ha/study/demand/command
  name: Study Demand
  payload_off: 'OFF'
  payload_on: 'ON'
  platform: mqtt
  retain: true
- command_topic: ha/lounge/demand/command
  name: Lounge Demand
  payload_off: 'OFF'
  payload_on: 'ON'
  platform: mqtt
  retain: true
- command_topic: ha/bedroom-mark/demand/command
  name: Mark's Bedroom Demand
  payload_off: 'OFF'
  payload_on: 'ON'
  platform: mqtt
  retain: true
- command_topic: ha/kitchen/demand/command
  name: Kitchen Demand
  payload_off: 'OFF'
  payload_on: 'ON'
  platform: mqtt
  retain: true
- command_topic: ha/ballroom/demand/command
  name: Ballroom Demand
  payload_off: 'OFF'
  payload_on: 'ON'
  platform: mqtt
  retain: true
- command_topic: ha/library/demand/command
  name: Library Demand
  payload_off: 'OFF'
  payload_on: 'ON'
  platform: mqtt
  retain: true
- command_topic: ha/hall/demand/command
  name: Hall Demand
  payload_off: 'OFF'
  payload_on: 'ON'
  platform: mqtt
  retain: true
thermostat: []

light:
 platform: rfxtrx
 automatic_add: True

switch:
 platform: rfxtrx
 automatic_add: True
