homeassistant:
  # Name of the location where Home Assistant is running
  name: WB
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 55
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - updater
      - device_tracker
    entities:
      - sun.sun   # Don't record sun data
  include:
    domains:
      - ups
      - switch
    entities:
      - sensor.horstmann_scsc17_thermostat_temperature_35_1
      - sensor.horstmann_scsc17_thermostat_temperature_50_1
      - sensor.aeotec_dsb05_multisensor_temperature_3_1
      - sensor.ballroom_east_temperature_33_1
      - sensor.hall_west_temperature_13_1
      - sensor.hall_east_temperature_24_1
      - sensor.annex_hall_temperature_43_1
      - sensor.kitchen_temperature_34_1
      - sensor.library_temperature_25_1
      - sensor.lounge_east_temperature_30_1
      - sensor.bedroom_mark_temperature_29_1
      - sensor.study_east_temperature_14_1
      - sensor.study_west_temperature_15_1
      - sensor.bedroom_jerome_temperature_44_1
      - sensor.bedroom_ros_temperature_55_1
      - sensor.main_heating_thermostat_battery
      - sensor.annex_heating_thermostat_battery
      - sensor.hall_multisensor_battery
      - sensor.hall_west_battery
      - sensor.study_east_battery
      - sensor.study_west_battery
      - sensor.hall_east_battery
      - sensor.library_battery
      - sensor.bedroom_mark_battery
      - sensor.lounge_east_battery
      - sensor.ballroom_east_battery
      - sensor.kitchen_battery
      - sensor.annex_hall_battery
      - sensor.bedroom_jerome_battery
      - sensor.bedroom_ros_battery
      - sensor.aeotec_dsb05_multisensor_luminance_3_3
      - sensor.aeotec_dsb05_multisensor_relative_humidity_3_5
      - switch.greenwave_powernode_1_port_switch_53_0
      - sensor.greenwave_powernode_1_port_energy_53_0
      - sensor.greenwave_powernode_1_port_power_53_8

# Customize database
recorder:
  db_url: !secret db_url
  purge_days: 30

# Checks for available updates
updater:

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Track the sun
sun:

http:
  api_password: !secret api_password
#  base_url: !secret base_url

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1

zwave:
  usb_path: /dev/ttyUSB21
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml

rfxtrx:
  device: /dev/ttyUSB22
  debug: False

device_tracker: !include device_tracker.yaml

#ifttt:
#  key: !secret ifttt_key
#
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

#emulated_hue: !include emulated_hue.yaml
#
notify: !include_dir_merge_list notify
tts: !include tts.yaml

scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automation

group: !include groups.yaml

media_player: !include_dir_merge_list media_players
light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list thermostats
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
script: !include_dir_merge_named scripts
