homeassistant:
  # Name of the location where Home Assistant is running
  name: WB
  # Location required to calculate the time the sun rises and sets
  latitude: 52.23492
  longitude: -0.04496
  elevation: 55
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Track the sun
sun:

http:
  api_password: !secret api_password

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1

zwave:
  usb_path: /dev/ttyUSB21
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.0b9-py3.4-linux-armv7l.egg/config
  polling_interval: 60000

rfxtrx:
  device: /dev/ttyUSB22
  debug: False


device_tracker: !include device_tracker.yaml

ifttt:
  key: !secret ifttt_key

scene: !include scene.yaml
automation: !include_dir_merge_list automation

group: !include groups.yaml

media_player: !include media_players.yaml
light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list thermostats
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select

