homeassistant:
  # Name of the location where Home Assistant is running
  name: WB
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 55
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml
  packages:
    package_mark: !include people/mark.yaml
    package_anne: !include people/anne.yaml
    package_jerome: !include people/jerome.yaml
    package_ros: !include people/ros.yaml
    package_thomas: !include people/thomas.yaml
    package_liane: !include people/liane.yaml
    package_aneta: !include people/aneta.yaml
    package_monica: !include people/monica.yaml
    package_olga: !include people/olga.yaml
    package_elle: !include people/elle.yaml


    package_aeotec_multisensor: !include packages/aeotec_multisensor.yaml
    package_camera0: !include packages/dahua-cameras.yaml
    package_hottub: !include packages/hottub.yaml
    package_washing_machine: !include packages/washing-machine.yaml
    #package_stream_radio: !include packages/stream-radio.yaml
    package_oil_monitor: !include packages/myolive.yaml
    package_multiroom_audio: !include packages/multiroom_audio.yaml
    package_mode: !include packages/mode.yaml

    package_everwhere: !include packages/everywhere.yaml

    package_study: !include packages/study/room.yaml
    package_study_heating: !include packages/study/heating-on-demand.yaml
    package_study_mode: !include packages/study/mode.yaml
    package_study_settings: !include packages/study/settings.yaml
    package_study_voice_control: !include packages/study/voice-control.yaml

    package_kitchen: !include packages/kitchen/room.yaml
    package_kitchen_heating: !include packages/kitchen/heating-on-demand.yaml
    package_kitchen_mode: !include packages/kitchen/mode.yaml
    package_kitchen_settings: !include packages/kitchen/settings.yaml
    package_kitchen_voice_control: !include packages/kitchen/voice-control.yaml

    package_hall: !include packages/hall/room.yaml
    package_hall_heating: !include packages/hall/heating-on-demand.yaml
    package_hall_voice_control: !include packages/hall/voice-control.yaml
    package_annex_hall_heating: !include packages/hall/annex-hall-heating-on-demand.yaml
    package_annex_hall_voice_control: !include packages/hall/annex-hall-voice-control.yaml

    package_lounge: !include packages/lounge/room.yaml
    package_lounge_heating: !include packages/lounge/heating-on-demand.yaml
    package_lounge_media_dimming: !include packages/lounge/media-dimming.yaml
    package_lounge_mode: !include packages/lounge/mode.yaml
    package_lounge_settings: !include packages/lounge/settings.yaml
    package_lounge_voice_control: !include packages/lounge/voice-control.yaml

    package_library: !include packages/library/room.yaml
    package_library_heating: !include packages/library/heating-on-demand.yaml
    package_library_mode: !include packages/library/mode.yaml
    package_library_settings: !include packages/library/settings.yaml
    package_library_voice_control: !include packages/library/voice-control.yaml

    package_ballroom: !include packages/ballroom/room.yaml
    package_ballroom_heating: !include packages/ballroom/heating-on-demand.yaml
    package_ballroom_media_dimming: !include packages/ballroom/media-dimming.yaml
    package_ballroom_mode: !include packages/ballroom/mode.yaml
    package_ballroom_settings: !include packages/ballroom/settings.yaml
    package_ballroom_voice_control: !include packages/ballroom/voice-control.yaml

    package_armoury: !include packages/armoury/room.yaml

    package_guest_room: !include packages/guest_room/room.yaml
    package_guest_room_heating: !include packages/guest_room/heating-on-demand.yaml
    package_guest_room_mode: !include packages/guest_room/mode.yaml
    package_guest_room_settings: !include packages/guest_room/settings.yaml
    package_guest_room_voice_control: !include packages/guest_room/voice-control.yaml

    package_bedroom_mark: !include packages/bedroom-mark/room.yaml
    package_bedroom_mark_heating: !include packages/bedroom-mark/heating-on-demand.yaml
    package_bedroom_mark_media_dimming: !include packages/bedroom-mark/media-dimming.yaml
    package_bedroom_mark_mode: !include packages/bedroom-mark/mode.yaml
    package_bedroom_mark_settings: !include packages/bedroom-mark/settings.yaml
    package_bedroom_mark_voice_control: !include packages/bedroom-mark/voice-control.yaml

    # Jerome's room
    package_bedroom_main2: !include packages/bedroom-main2/room.yaml
    package_bedroom_main2_heating: !include packages/bedroom-main2/heating-on-demand.yaml
    package_bedroom_main2_mode: !include packages/bedroom-main2/mode.yaml
    package_bedroom_main2_settings: !include packages/bedroom-main2/settings.yaml
    package_bedroom_main2_voice_control: !include packages/bedroom-main2/voice-control.yaml

    # Tom's room
    package_bedroom_main3: !include packages/bedroom-main3/room.yaml
    package_bedroom_main3_heating: !include packages/bedroom-main3/heating-on-demand.yaml
    package_bedroom_main3_mode: !include packages/bedroom-main3/mode.yaml
    package_bedroom_main3_settings: !include packages/bedroom-main3/settings.yaml
    package_bedroom_main3_voice_control: !include packages/bedroom-main3/voice-control.yaml

    # Ros's room
    package_bedroom_annex2: !include packages/bedroom-annex2/room.yaml
    package_bedroom_annex2_heating: !include packages/bedroom-annex2/heating-on-demand.yaml
    package_bedroom_annex2_mode: !include packages/bedroom-annex2/mode.yaml
    package_bedroom_annex2_settings: !include packages/bedroom-annex2/settings.yaml
    package_bedroom_annex2_voice_control: !include packages/bedroom-annex2/voice-control.yaml

    #package_room: !include packages/room/room.yaml

    # usb0 decomissioned
    package_modem_scraper: !include packages/modem_scraper.yaml

    # dash button automations
    package_dinner_time: !include packages/dinner-time.yaml
    package_party_mode: !include packages/party-mode.yaml
    package_table_tennis: !include packages/table-tennis.yaml

config:
discovery:

zone: !include zone.yaml

# Deps: camera
ffmpeg:

# Allows you to issue voice commands from the frontend
conversation:

logger:
  default: error

# Enables support for tracking state changes over time.
history: !include history.yaml

# View all events in a logbook
logbook: !include logbook.yaml

# Customize database
recorder:
  db_url: !secret db_url
  purge_keep_days: 10

influxdb: !include influxdb.yaml


# Checks for available updates
updater:

# Enables the frontend
frontend:

map:

# Track the sun
sun:

http:
#  base_url: !secret base_url

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant
  keepalive: 60
  discovery: true
  discovery_prefix: ha

rfxtrx:
  device: /dev/ttyUSB22
  debug: false
  automatic_add: true
  devices: !include rfxtrx_devices.yaml


device_tracker: !include device_tracker.yaml

#ifttt:
#  key: !secret ifttt_key
#
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

notify: !include_dir_merge_list notify
ios:
tts: !include tts.yaml

automation: !include_dir_merge_list automation

group: !include groups.yaml

media_player: !include_dir_merge_list media_players
light: !include_dir_merge_list lights
#sensor: !include_dir_merge_list sensors
#binary_sensor: !include_dir_merge_list binary_sensors
switch: !include_dir_merge_list switches
#climate: !include_dir_merge_list thermostats
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
script: !include_dir_merge_named scripts

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

lovelace:
  mode: yaml

owntracks:
  max_gps_accuracy: 3000

google_assistant: !include google-assistant.yaml
mobile_app:
