#- platform: snmp
#  host: 192.168.7.1
#  community: public
#  baseoid: 1.3.6.1.2.1.4.22.1.2
#  track_new_devices: yes
#  interval_seconds: 30
#  consider_home: 180

- platform: owntracks
  max_gps_accuracy: 3000

- platform: nmap_tracker
  hosts: 192.168.6.1-254 192.168.7.1-254
  interval_seconds: 60
  home_interval: 20
  track_new_devices: yes
  consider_home: 1800
  exclude:
    - 192.168.7.3

- platform: bluetooth_tracker

#- platform: ubus
#  host: 192.168.7.1
#  username: root
#  password: XXXX

## Needs either a valid cert or set
##  PYTHONWARNINGS="ignore:Unverified HTTPS request"
##
#- platform: unifi
#  host: cyclops
#  username: viewer
#  password: !secret unifi_password
#  verify_ssl: false

- platform: tado
  username: !secret tado_username
  password: !secret tado_password
  home_id: !secret tado_home_id

