name: Whale Barn
views:
  - title: Home
    icon: mdi:home
    badges:
      - sensor.study_temperature
      - sensor.kitchen_mean_temperature
      - sensor.hall_temperature
      - sensor.annex_hall_mean_temperature
      - sensor.lounge_temperature
      - sensor.library_mean_temperature
      - sensor.ballroom_temperature
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          title: Where is Everyone?
          show_header_toggle: false
          entities:
            - entity: binary_sensor.mark_present
              name: Mark
            - entity: binary_sensor.anne_present
              name: Anne
            - entity: binary_sensor.thomas_present
              name: Thomas
            - entity: binary_sensor.monica_present
              name: Monica
        - type: entity-filter
          entities:
            - entity: binary_sensor.jerome_present
              name: Jerome
            - entity: binary_sensor.ros_present
              name: Ros
            - entity: binary_sensor.liane_present
              name: Liane
            - entity: binary_sensor.aneta_present
              name: Aneta
          state_filter:
            - "on"
          show_empty: false
      - type: entities
        title: Rooms
        show_header_toggle: false
        entities:
          - input_select.study_mode
          - input_select.kitchen_mode
          - input_select.lounge_mode
          - input_select.library_mode
          - input_select.ballroom_mode
      - type: entities
        title: Bedrooms
        show_header_toggle: false
        entities:
          - entity: input_select.bedroom_mark_mode
            name: "Mark's Bedroom Mode"
          - entity: input_select.bedroom_jerome_mode
            name: "Jerome's Bedroom Mode"
          - entity: input_select.bedroom_annex2_mode
            name: "Monica's Bedroom Mode"
          - entity: input_select.guest_room_mode
            name: "Guest Room Mode"

  - title: Bedrooms
    icon: mdi:hotel
    badges:
      - sensor.bedroom_mark_temperature
      - sensor.bedroom_annex2_mean_temperature
      - sensor.bedroom_jerome_mean_temperature
      - sensor.js_bedroom_humidity
      - sensor.guest_room_mean_temperature
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Mark's Bedroom
            show_header_toggle: false
            entities:
              - input_select.bedroom_mark_mode
              - climate.bedroom_mark_thermostat
              - group.bedroom_mark_lights
              - group.g_bedroom_mark_media_dimming
              - group.g_bedroom_mark_settings_ui
          - type: media-control
            entity: media_player.bedroom_mark

      - type: vertical-stack
        cards:
          - type: entities
            title: Jerome's Bedroom
            show_header_toggle: false
            entities:
              - input_select.bedroom_jerome_mode
              - climate.j_s_bedroom
              - group.g_bedroom_jerome_settings_ui

      - type: vertical-stack
        cards:
          - type: entities
            title: "Monica's Bedroom"
            show_header_toggle: false
            entities:
              - entity: input_select.bedroom_annex2_mode
                name: "Monica's Bedroom Mode"
              - entity: climate.bedroom_annex2_thermostat
                name: "Monica's Bedroom"
              - group.g_bedroom_annex2_settings_ui

      - type: vertical-stack
        cards:
          - type: entities
            title: Guest Room
            show_header_toggle: false
            entities:
              - input_select.guest_room_mode
              - climate.guest_room_thermostat
              - group.g_guest_room_settings_ui

  - title: Study
    icon: mdi:printer
    badges:
      - sensor.study_temperature
    cards:
      - type: entities
        title: Study
        show_header_toggle: false
        entities:
          - input_select.study_mode
          - climate.study_thermostat
          - entity: binary_sensor.heiman_contact_65_sensor
            name: "Study Door Open"
          - group.g_study_settings_ui
      - type: entities
        title: Study Appliances
        show_header_toggle: false
        entities:
          - device_tracker.ricoh213w
          - device_tracker.canonmg5550
      - type: media-control
        entity: media_player.study

  - title: Kitchen
    icon: mdi:stove
    badges:
      - sensor.kitchen_mean_temperature
      - sensor.greenwave_powernode_54_energy
      - sensor.greenwave_powernode_54_power
    cards:
      - type: entities
        title: Kitchen
        show_header_toggle: false
        entities:
          - input_select.kitchen_mode
          - climate.kitchen_thermostat
          - binary_sensor.washing_machine
          - entity: binary_sensor.heiman_contact_66_sensor
            name: "Gin Freezer Open"
          - group.g_kitchen_settings_ui
      - type: media-control
        entity: media_player.kitchen_speaker
      - type: media-control
        entity: media_player.outside_amplifier_zone_2

  - title: Hall
    icon: mdi:fullscreen-exit
    badges:
      - binary_sensor.aeotec_dsb05_multisensor_sensor
      - sensor.aeotec_dsb05_multisensor_luminance
      - sensor.aeotec_dsb05_multisensor_relative_humidity
      - sensor.aeotec_dsb05_multisensor_temperature
      - sensor.hall_temperature
      - sensor.annex_hall_mean_temperature
    cards:
      - type: entities
        title: Hall
        show_header_toggle: false
        entities:
          - climate.hall_thermostat
          - climate.annex_hall_thermostat
          - entity: binary_sensor.heiman_contact_63_sensor
            name: "Front Door Open"
      - type: entities
        title: Main Heating
        entities:
          - sensor.main_heating_thermostat_temperature
          - climate.main_heating_thermostat_heating_1
          - switch.main_heating_thermostat_switch
      - type: entities
        title: Annex Heating
        show_header_toggle: false
        entities:
          - sensor.annex_heating_thermostat_temperature
          - climate.annex_heating_thermostat_heating_1
          - switch.annex_heating_thermostat_switch
      - type: entities
        title: Hot Tub
        show_header_toggle: false
        entities:
          - binary_sensor.hottub
          - switch.greenwave_powernode_53_switch
          - sensor.greenwave_powernode_53_energy
          - sensor.greenwave_powernode_53_power
      - type: entities
        title: Oil Levels
        show_header_toggle: false
        entities:
          - sensor.oil_main_litres
          - sensor.oil_main_percentage
          - sensor.oil_main_days_remaining
          - sensor.oil_annex_litres
          - sensor.oil_annex_percentage
          - sensor.oil_annex_days_remaining
      - type: media-control
        entity: media_player.outside_amplifier

  - title: Lounge
    icon: mdi:sofa
    badges:
      - sensor.lounge_temperature
    cards:
      - type: entities
        title: Lounge
        show_header_toggle: false
        entities:
          - input_select.lounge_mode
          - climate.lounge_thermostat
          - group.lounge_lights
          - group.g_lounge_media_dimming
          - group.g_lounge_settings_ui
      - type: media-control
        entity: media_player.lounge

  - title: Library
    icon: mdi:library
    badges:
      - sensor.library_mean_temperature
    cards:
      - type: entities
        title: Library
        show_header_toggle: false
        entities:
          - input_select.library_mode
          - climate.library_thermostat
          - group.g_library_settings_ui
      - type: media-control
        entity: media_player.library

  - title: Ballroom
    icon: mdi:projector
    badges:
      - sensor.ballroom_temperature
    cards:
      - type: entities
        title: Ballroom
        show_header_toggle: false
        entities:
          - input_select.ballroom_mode
          - climate.ballroom_thermostat
          - group.ballroom_party_lights
          - group.g_ballroom_media_dimming
          - group.g_ballroom_settings_ui
      - type: media-control
        entity: media_player.ballroom
      - type: media-control
        entity: media_player.ballroom_amplifier

  - title: Armoury
    icon: mdi:security
    badges:
      - sensor.cm2_temp_c
      - sensor.cm2_humidity
      - sensor.cm2_light
      - sensor.cm2_airflow
      - sensor.cm2_sound
      - sensor.cm2_dew_point_c
    cards:
      - type: entities
        title: Network
        show_header_toggle: false
        entities:
          - device_tracker.router
          - device_tracker.climate
          - device_tracker.ap_west
          - device_tracker.ap_central
          - device_tracker.ap_east
          - device_tracker.poe_switch
          - device_tracker.olive_hub
          - device_tracker.cyclops
          - device_tracker.study
          - device_tracker.kitchen_tablet
          - device_tracker.amazon_92f1b9374
          - device_tracker.kitchen_speaker
          - device_tracker.utilityamp
          - device_tracker.outside
          - device_tracker.lounge
          - device_tracker.loungetv
          - device_tracker.ballroom
          - device_tracker.ballroomamp
          - device_tracker.library
          - device_tracker.library_wired
          - device_tracker.library_tablet
          - device_tracker.bedroommark
          - device_tracker.camera0
          - device_tracker.ricoh213w
          - device_tracker.canonmg5550
      - type: entities
        title: UPS
        show_header_toggle: false
        entities:
          - sensor.eaton_ups_status_data
          - sensor.eaton_ups_load
          - sensor.eaton_ups_battery_charge
          - sensor.eaton_ups_battery_runtime

  - title: Multiroom Audio
    icon: mdi:music
    cards:
      - type: media-control
        entity: media_player.mpd
      - type: entities
        title: Snapcast Volume
        show_header_toggle: false
        entities:
          - input_number.snapcast_client_study
          - input_number.snapcast_client_kitchen2
          - input_number.snapcast_client_lounge
          - input_number.snapcast_client_library
          - input_number.snapcast_client_ballroom
          - input_number.snapcast_client_bedroom_mark
          - input_number.snapcast_client_outside
      - type: media-control
        entity: media_player.snapcast_client_study
      - type: media-control
        entity: media_player.snapcast_client_kitchen2
      - type: media-control
        entity: media_player.snapcast_client_lounge
      - type: media-control
        entity: media_player.snapcast_client_library
      - type: media-control
        entity: media_player.snapcast_client_ballroom
      - type: media-control
        entity: media_player.snapcast_client_bedroom_mark
      - type: media-control
        entity: media_player.snapcast_client_outside

  - title: Settings
    icon: mdi:settings
    cards:
      - type: entities
        title: Main Heating Demand
        show_header_toggle: true
        entities:
          - switch.kitchen_demand
          - switch.lounge_demand
          - switch.library_demand
          - switch.ballroom_demand
          - switch.guest_room_demand
          - switch.bedroom_mark_demand
          - switch.bedroom_jerome_demand
      - type: entities
        title: Annex Heating Demand
        show_header_toggle: true
        entities:
          - switch.study_demand
          - switch.annex_hall_demand
          - switch.bedroom_annex2_demand
      - type: entities
        title: Temperatures
        show_header_toggle: false
        entities:
          - sensor.main_heating_thermostat_temperature
          - sensor.annex_heating_thermostat_temperature
          - sensor.aeotec_dsb05_multisensor_temperature
          - sensor.ballroom_east_temperature
          - sensor.hall_west_temperature
          - sensor.hall_east_temperature
          - sensor.annex_hall_temperature
          - sensor.kitchen_temperature
          - sensor.library_temperature
          - sensor.lounge_east_temperature
          - sensor.bedroom_mark_south_current_temperature
          - sensor.bedroom_mark_north_current_temperature
          - sensor.study_east_current_temperature
          - sensor.study_west_current_temperature
          - sensor.js_bedroom_temperature
          - sensor.bedroom_annex2_current_temperature
      - type: entities
        title: Thermostats
        show_header_toggle: false
        entities:
          - climate.annex_hall_thermostat
          - climate.ballroom_thermostat
          - climate.bedroom_mark_thermostat
          - climate.hall_thermostat
          - climate.kitchen_thermostat
          - climate.library_thermostat
          - climate.lounge_thermostat
          - climate.study_thermostat
          - climate.guest_room_thermostat
          - climate.bedroom_jerome_thermostat
          - climate.bedroom_annex2_thermostat
      - type: entities
        title: Thermostat Devices
        show_header_toggle: false
        entities:
          - climate.annex_hall_comfort_setpoint
          - climate.ballroom_east_comfort_setpoint
          - climate.bedroom_mark_south_comfort_setpoint
          - climate.bedroom_mark_north_comfort_setpoint
          - climate.hall_east_comfort_setpoint
          - climate.hall_west_comfort_setpoint
          - climate.main_heating_thermostat_heating_1
          - climate.annex_heating_thermostat_heating_1
          - climate.kitchen_comfort_setpoint
          - climate.library_comfort_setpoint
          - climate.lounge_east_comfort_setpoint
          - climate.study_east_comfort_setpoint
          - climate.study_west_comfort_setpoint
          - climate.guest_room_heat
          - climate.danfoss_z_thermostat_014g0013_heating_1
          - climate.bedroom_annex2_comfort_setpoint
          - climate.j_s_bedroom
      - type: entities
        title: Battery Levels
        show_header_toggle: false
        entities:
          - sensor.main_heating_thermostat_battery
          - sensor.annex_heating_thermostat_battery
          - sensor.hall_multisensor_battery
          - sensor.hall_west_battery
          - sensor.hall_east_battery
          - sensor.study_east_battery
          - sensor.study_west_battery
          - sensor.library_battery
          - sensor.bedroom_mark_south_battery
          - sensor.bedroom_mark_north_battery
          - sensor.lounge_east_battery
          - sensor.ballroom_east_battery
          - sensor.kitchen_battery
          - sensor.annex_hall_battery
          - sensor.bedroom_annex2_battery
          - sensor.guest_room_battery
      - type: entities
        title: Main Heating Override
        show_header_toggle: false
        entities:
          - switch.main_heating_relay_switch
          - switch.main_heating_relay_hot_water
          - automation.main_boiler_demand_on
          - automation.main_boiler_demand_off
          - automation.hot_water_on
          - automation.hot_water_off
      - type: entities
        title: Annex Heating Override
        show_header_toggle: false
        entities:
          - switch.annex_heating_relay_switch
          - automation.annex_thermostat_demand_on
          - automation.annex_thermostat_demand_off
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          #- automation.guest_room_sleep_time
          #- automation.guest_room_off_time
          #- automation.kitchen_cosy_time
          - automation.bedroom_mark_sleep_time
          - automation.bedroom_mark_off_time
          - automation.reset_modes
          #- automation.study_work_time
          - automation.calendar_scene
          - automation.calendar_climate
          - automation.calendar_mark_scene
          - automation.calendar_mark_climate
          - automation.calendar_jerome_scene
          - automation.calendar_jerome_climate
          #- automation.calendar_ros_scene
          #- automation.calendar_ros_climate
      - type: entities
        title: RFX Switches
        show_header_toggle: true
        entities:
          - switch.0a140003f15c7202010080
          - switch.0a140006f15c7203010080
          - switch.0a140009f3cf3510020080
          - switch.0a140002f40fa810020050
          - switch.0a140001f40fa810050040
          - switch.0a14000cf40fa910020040
          - switch.0a140083f3cf3510020070
          - switch.0a140084f3cf3510030070
          - switch.0a140087f3cf3510040070
          - switch.0a140086f3cf3510050070
      - type: entities
        title: RFX Lights
        show_header_toggle: true
        entities:
          - switch.0a140000f40fa801010050
          - switch.0a140016f3cf3501010080
          - switch.0a140022f3cf3502010080
          - switch.0a140023f3cf3503010080
          - switch.0a140024f3cf3504010080
          - switch.0a140000f15c7201010080
      - type: entities
        title: Amazon Dash Buttons
        show_header_toggle: false
        entities:
          - switch.table_tennis
          - switch.party_mode
          - switch.dinner_time
          - switch.ariel
          - switch.optimum_nutrition
          - switch.philips_sonicare
          - switch.right_guard

