sensor.hall_west_temperature:
  polling_intensity: 5
sensor.study_east_temperature:
  polling_intensity: 5
sensor.study_west_temperature:
  polling_intensity: 5
sensor.hall_east_temperature:
  polling_intensity: 5
sensor.library_temperature:
  polling_intensity: 5
sensor.bedroom_mark_temperature:
  polling_intensity: 5
sensor.lounge_east_temperature:
  polling_intensity: 5
sensor.ballroom_east_temperature:
  polling_intensity: 5
sensor.kitchen_temperature:
  polling_intensity: 5
sensor.annex_hall_temperature:
  polling_intensity: 5
sensor.bedroom_jerome_temperature:
  polling_intensity: 5
sensor.bedroom_ros_temperature:
  polling_intensity: 5
