sensor.hall_west_temperature:
  polling_intensity: 5
  ignored: false
sensor.study_east_temperature:
  polling_intensity: 5
  ignored: false
sensor.study_west_temperature:
  polling_intensity: 5
  ignored: false
sensor.hall_east_temperature:
  polling_intensity: 5
  ignored: false
sensor.library_temperature:
  polling_intensity: 5
  ignored: false
sensor.bedroom_mark_south_temperature:
  polling_intensity: 5
  ignored: false
sensor.bedroom_mark_north_temperature:
  polling_intensity: 5
  ignored: false
sensor.lounge_east_temperature:
  polling_intensity: 5
  ignored: false
sensor.ballroom_east_temperature:
  polling_intensity: 5
  ignored: false
sensor.kitchen_temperature:
  polling_intensity: 5
  ignored: false
sensor.annex_hall_temperature:
  polling_intensity: 5
  ignored: false
sensor.bedroom_annex2_temperature:
  polling_intensity: 5
  ignored: false
sensor.guest_room_temperature:
  ignored: false
  polling_intensity: 5
sensor.spiritz_70_temperature:
  ignored: false
  polling_intensity: 5
