- alias: guest_room_sleep_time
  trigger:
    - platform: time
      at: '03:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.guest_room_mode
        option: "Sleep"

- alias: guest_room_off_time
  trigger:
    - platform: time
      at: '09:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.guest_room_mode
        option: "Off"
