homeassistant:
  customize:
    climate.ballroom_thermostat:
      friendly_name: "Ballroom Heating"
    sensor.ballroom_temperature:
      friendly_name: "Ballroom"
      icon: mdi:thermometer
      unit_of_measurement: "\xB0C"

group:
  g_debug_ballroom_heating:
    entities:
      - climate.ballroom_thermostat
      - climate.ballroom_east_thermostat
      - switch.ballroom_demand

  # Non-UI group which forwards setpoint updates
  #  Name is mapped from climate.foo_thermostat -> group.g_foo_thermostat
  g_ballroom_thermostat:
    entities:
      - climate.ballroom_east_thermostat

climate:
  - name: ballroom_thermostat
    platform: generic_thermostat
    heater: switch.ballroom_demand
    target_sensor: sensor.ballroom_temperature
    max_temp: 25
    min_temp: 5
    target_temp: 5.0

switch:
  - name: ballroom_demand
    platform: mqtt
    command_topic: ha/ballroom/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

sensor:
  - name: ballroom_east_current_temperature
    platform: mqtt
    state_topic: 'zwave/ballroom_east/49/0/Air_temperature'
    value_template: '{{ value_json.value }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: ballroom_temperature
    platform: min_max
    type: max  # minimize occasional 0 readings. Replace with median?
    entity_ids:
      - sensor.ballroom_east_current_temperature

  - platform: template
    sensors:
      ballroom_setpoint:
        value_template: "{{ states.climate.ballroom_thermostat.attributes.temperature }}"
        unit_of_measurement: "\xB0C"
