#
# Mode selection
#
# Stores last user intent.
# Reverts to manual when user adjustments are made.
#

input_select:
  ballroom_mode:
    name: Ballroom Mode
    options:
      - 'Off'
      - 'Party'
      - 'Bright'
      - 'Movie'
      - 'Manual'
    initial: 'Off'
    icon: mdi:projector

input_number:
  ballroom_temperature_off:
    name: 'Off Temp'
    initial: 5
    <<: &ballroom_temp_defaults
      icon: mdi:thermostat
      unit_of_measurement: "\xB0C"
      min: 5
      max: 25
      step: 1

  ballroom_temperature_party:
    name: 'Party Temp'
    initial: 20
    <<: *ballroom_temp_defaults

  ballroom_temperature_bright:
    name: 'Bright Temp'
    initial: 20
    <<: *ballroom_temp_defaults

  ballroom_temperature_movie:
    name: 'Movie Temp'
    initial: 20
    <<: *ballroom_temp_defaults

automation:
  - alias: ballroom_revert_to_manual
    trigger:
      - platform: state
        entity_id:
          - group.ballroom_lights
          - group.ballroom_party_lights
          - sensor.ballroom_setpoint
    #condition:
    #  condition: template  # otherwise we reset on all state updates
    #  value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
        - service: input_select.select_option
          data:
            entity_id: input_select.ballroom_mode
            option: 'Manual'


  - alias: ballroom_mode
    trigger:
      - platform: state
        entity_id: input_select.ballroom_mode
    action:
      - service: script.set_mode
        data_template:
          room: 'ballroom'
          mode: '{{ trigger.to_state.state | lower }}'
