#
# Ballroom
#

homeassistant:
  customize:
    sensor.ballroom_east_air_temperature:
      friendly_name: Ballroom East
    sensor.ballroom_east_battery_level:
      friendly_name: Ballroom East Battery
      icon: mdi:battery

    switch.greenwave_powernode_24_switch:
      friendly_name: Ballroom Disco Light
      entity_picture: /local/wb-icons/ext_mirrorball.png

    climate.ballroom_east_mode:
      min_temp: 5
      max_temp: 25

    # FIXME: media-control card ignores 'name' settings
    media_player.ballroom_amplifier:
      friendly_name: Ballroom Amplifier

group:
  # floorplan
  ballroom_compact_ui:
    name: Ballroom
    icon: mdi:projector
    entities:
    - input_select.ballroom_mode
    - climate.ballroom_thermostat
    - group.ballroom_party_lights

  ballroom_setpoints:
    name: Ballroom Setpoints
    entities:
    - climate.ballroom_east_mode

  ballroom_lights:
    name: Ballroom Lights
    icon: mdi:lightbulb-on

  ballroom_party_lights:
    name: Ballroom Party Lights
    icon: mdi:lightbulb-on
    entities:
    - switch.greenwave_powernode_24_switch

scene:
  - name: ballroom_off
    entities:
      group.ballroom_lights:
        state: off
      group.ballroom_party_lights:
        state: off
      media_player.ballroom:
        state: paused
      media_player.ballroom_amplifier:
        state: off
      media_player.snapcast_client_ballroom:
        state: on
        is_volume_muted: true

  - name: ballroom_party
    entities:
      group.ballroom_lights:
        state: on
        brightness_pct: 20
      group.ballroom_party_lights:
        state: on

  - name: ballroom_movie
    entities:
      group.ballroom_lights:
        state: off
      group.ballroom_party_lights:
        state: off

  - name: ballroom_bright
    entities:
      group.ballroom_lights:
        state: on
        brightness_pct: 100
      group.ballroom_party_lights:
        state: off

switch:
  - name: Ballroom Demand
    platform: mqtt
    command_topic: ha/ballroom/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

media_player:
  - name: ballroom
    platform: kodi
    host: ballroom
    port: 80

  - name: Ballroom Amplifier
    platform: onkyo
    host: ballroom-amp
    sources:
      #dvd: 'BD/DVD'
      video2: 'TV'
      video1: 'Media'
      #video3: 'Game'
      video6: 'Aux Cable'
      #aux1: 'Ext Aux'
      #cd: 'Analog TV'
      #phono: 'Phono' # -> needs onkyo fix
      fm: 'FM' # -> needs onkyo fix
      am: 'AM' # -> needs onkyo fix
      network: 'Network'
      usb: 'USB'

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
