group:
  g_ballroom_settings_ui:
    name: Settings
    icon: mdi:settings
    control: hidden
    entities:
      - input_number.ballroom_temperature_off
      - input_number.ballroom_temperature_party
      - input_number.ballroom_temperature_bright
      - input_number.ballroom_temperature_movie

