group:
  g_bedroom_jerome_settings_ui:
    name: Settings
    icon: mdi:settings
    control: hidden
    entities:
      - input_number.bedroom_jerome_temperature_off
      - input_number.bedroom_jerome_temperature_sleep
      - input_number.bedroom_jerome_temperature_cosy


