homeassistant:
  customize:
    group.jerome_present:
      entity_picture: &ep /local/wb-icons/wb_jerome.png
    binary_sensor.jerome_present:
      entity_picture: *ep
    device_tracker.jerome_phone:
      entity_picture: *ep
      friendly_name: "Jerome Owntracks"

group:
  jerome_present:
    name: "Jerome"
    entities: &presence_entities
      - device_tracker.jerome_phone
      - device_tracker.jerome_android
      - device_tracker.jeromes_phone
        #- device_tracker.jerome_android_bt
        #- device_tracker.jdilley_macbookpro
        #- device_tracker.jdilley_macbookpro_wired
      - device_tracker.jerome_asus
      - device_tracker.jerome_asus_bt

binary_sensor:
  - name: jerome_present
    device_class: 'presence'
    platform: 'bayesian'
    prior: 0.20
    probability_threshold: 0.90
    observations:
      # Owntracks
      - entity_id: device_tracker.jerome_phone
        prob_given_true: 0.4
        prob_given_false: 0.2
        <<: &tracker_default
          platform: 'state'
          to_state: 'home'

      - entity_id: device_tracker.jerome_android
        prob_given_true: 0.8
        prob_given_false: 0.1
        <<: *tracker_default

      - entity_id: device_tracker.jeromes_phone
        prob_given_true: 0.5
        prob_given_false: 0.1
        <<: *tracker_default
        #- entity_id: device_tracker.jerome_android_bt
        #- entity_id: device_tracker.jdilley_macbookpro
        #- entity_id: device_tracker.jdilley_macbookpro_wired

      - entity_id: device_tracker.jerome_asus
        prob_given_true: 0.5
        prob_given_false: 0.1
        <<: *tracker_default

      - entity_id: device_tracker.jerome_asus_bt
        prob_given_true: 0.5
        prob_given_false: 0.1
        <<: *tracker_default

automation:
  - alias: "Calendar Jerome Scene"
    initial_state: off
    trigger:
      - platform: state
        entity_id: calendar.jerome_scene
        to: "on"
    action:
      - service_template: input_select.select_option
        data_template:
          entity_id: >
            {% set l = trigger.to_state.attributes.message.lower().split() %}
            {% if "jerome" in l %}
            {%   set u = "bedroom_jerome" %}
            {% endif %}
            input_select.{{u}}_mode
          option: >
            {% set v = trigger.to_state.attributes.message.lower().split()|last %}
            {{ v[0].upper() ~ v[1:].lower() }}
      - service: mqtt.publish
        data_template:
          topic: 'ha/calendar/jerome-scene'
          payload: '{{trigger.to_state.attributes.message}}'

  - alias: "Calendar Jerome Climate"
    initial_state: off
    trigger:
      - platform: state
        entity_id: calendar.jerome_climate
        to: "on"
    action:
      - service_template: climate.set_temperature
        data_template:
          entity_id: >
            {% set l = trigger.to_state.attributes.message.lower().split() %}
            {% if "jerome" in l %}
            {%   set u = "bedroom_jerome" %}
            {% endif %}
            climate.{{u}}_thermostat
          temperature: >
            {% set l = trigger.to_state.attributes.message.lower().split() %}
            {{l|last|float}}
      - service: mqtt.publish
        data_template:
          topic: 'ha/calendar/jerome-climate'
          payload: '{{trigger.to_state.attributes.message}}'

