homeassistant:
  customize:
    group.monica_present:
      entity_picture: &ep /local/wb-icons/wb_monica.png
    binary_sensor.monica_present:
      entity_picture: *ep
    device_tracker.monica_phone:
      entity_picture: *ep
      friendly_name: "Monica Owntracks"

group:
  monica_present:
    name: "Monica"
    entities: &presence_entities
    - device_tracker.moncoms_iphone
    - device_tracker.monica_phone
    - device_tracker.monica_iphone
    - device_tracker.monica_macbook_pro
    - device_tracker.monica_macbook_pro_bt

binary_sensor:
  - name: monica_present
    device_class: 'presence'
    platform: 'bayesian'
    prior: 0.66
    probability_threshold: 0.90
    observations:
      ## Owntracks
      #- entity_id: device_tracker.monica_phone
      #  prob_given_true: 0.4
      #  prob_given_false: 0.2
      #  platform: 'state'
      #  to_state: 'home'

      # ios platform - loc doesn't update very often
      - entity_id: device_tracker.moncoms_iphone
        prob_given_true: 0.4
        prob_given_false: 0.2
        <<: &tracker_default
          platform: 'state'
          to_state: 'home'

      - entity_id: device_tracker.monica_iphone
        prob_given_true: 0.8
        prob_given_false: 0.1
        <<: *tracker_default

      - entity_id: device_tracker.monica_macbook_pro
        prob_given_true: 0.5
        prob_given_false: 0.1
        <<: *tracker_default

      - entity_id: device_tracker.monica_macbook_pro_bt
        prob_given_true: 0.3
        prob_given_false: 0.1
        <<: *tracker_default

automation:
  - alias: "Calendar Monica Scene"
    trigger:
      - platform: state
        entity_id: calendar.monica_scene
        to: "on"
    action:
      - service_template: input_select.select_option
        data_template:
          entity_id: >
            {% set l = trigger.to_state.attributes.message.lower().split() %}
            {% if "monica" in l %}
            {%   set u = "bedroom_annex2" %}
            {% endif %}
            input_select.{{u}}_mode
          option: >
            {% set v = trigger.to_state.attributes.message.lower().split()|last %}
            {{ v[0].upper() ~ v[1:].lower() }}
      - service: mqtt.publish
        data_template:
          topic: 'ha/calendar/monica-scene'
          payload: '{{trigger.to_state.attributes.message}}'

  - alias: "Calendar Monica Climate"
    trigger:
      - platform: state
        entity_id: calendar.monica_climate
        to: "on"
    action:
      - service_template: climate.set_temperature
        data_template:
          entity_id: >
            {% set l = trigger.to_state.attributes.message.lower().split() %}
            {% if "monica" in l %}
            {%   set u = "bedroom_annex2" %}
            {% endif %}
            climate.{{u}}_thermostat
          temperature: >
            {% set l = trigger.to_state.attributes.message.lower().split() %}
            {{l|last|float}}
      - service: mqtt.publish
        data_template:
          topic: 'ha/calendar/monica-climate'
          payload: '{{trigger.to_state.attributes.message}}'

