#
# Mode selection
#
# Stores last user intent.
# Reverts to manual when user adjustments are made.
#

input_select:
  library_mode:
    name: Library Mode
    options:
      - 'Off'
      - 'Cosy'
      - 'Bright'
      - 'Read'
      - 'Manual'
    initial: 'Off'
    icon: mdi:library

input_number:
  library_temperature_off:
    name: 'Off Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 10
    step: 1

  library_temperature_cosy:
    name: 'Cosy Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 22
    step: 1

  library_temperature_bright:
    name: 'Bright Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 20
    step: 1

  library_temperature_read:
    name: 'Read Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 22
    step: 1

automation:
  - alias: library_revert_to_manual
    trigger:
      - platform: state
        entity_id:
          - group.library_lights
          - sensor.library_setpoint
    #condition:
    #  condition: template  # otherwise we reset on all state updates
    #  value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
        - service: input_select.select_option
          data:
            entity_id: input_select.library_mode
            option: 'Manual'


  - alias: library_mode
    trigger:
      - platform: state
        entity_id: input_select.library_mode
    action:
      - service: script.set_mode
        data_template:
          room: 'library'
          mode: '{{ trigger.to_state.state | lower }}'
