#
# Library
#

homeassistant:
  customize:
    sensor.library_temperature:
      friendly_name: Library
    sensor.library_battery:
      friendly_name: Library Battery
      icon: mdi:battery

    climate.library_mode:
      min_temp: 5
      max_temp: 25

group:
  # floorplan
  library_compact_ui:
    name: Library
    icon: mdi:library
    entities:
    - input_select.library_mode
    - climate.library_thermostat
    - group.library_lights

  library_setpoints:
    name: Library Setpoints
    entities:
    - climate.library_mode

  library_lights:
    name: Library Lights

scene:
  - name: library_off
    entities:
      group.library_lights:
        state: off
      media_player.library:
        state: paused
      media_player.snapcast_client_library:
        state: on
        is_volume_muted: true

  - name: library_cosy
    entities:
      group.library_lights:
        state: on
        brightness_pct: 50

  - name: library_bright
    entities:
      group.library_lights:
        state: on
        brightness_pct: 100

  - name: library_read
    entities:
      group.library_lights:
        state: on
        brightness_pct: 100

sensor:
  - platform: template
    sensors:
      library_battery:
        value_template: >
          {% if states.zwave.library %}
            {{ states.zwave.library.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: '%'
        entity_id: zwave.library

media_player:
  - name: library
    platform: volumio
    host: library
    port: 3000

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
