#
# Library
#

homeassistant:
  customize:
    climate.library_east_thermostat:
      min_temp: 5
      max_temp: 25

group:
  # floorplan
  library_compact_ui:
    name: Library
    icon: mdi:library
    entities:
      - input_select.library_mode
      - climate.library_thermostat
      - group.library_lights
      - media_player.library_multizone_audio

  library_setpoints:
    name: Library Setpoints
    entities:
      - climate.library_east_thermostat

  library_lights:
    name: Library Lights

scene:
  - name: library_off
    entities:
      group.library_lights:
        state: off
      media_player.library_multizone_audio:
        state: paused

  - name: library_cosy
    entities:
      group.library_lights:
        state: on
        brightness_pct: 50

  - name: library_bright
    entities:
      group.library_lights:
        state: on
        brightness_pct: 100

  - name: library_read
    entities:
      group.library_lights:
        state: on
        brightness_pct: 100

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
