- platform: template
  sensors:
    library_battery:
      value_template: >
        {% if states.zwave.library %}
          {{ states.zwave.library.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
