group:
  g_library_settings_ui:
    name: Settings
    icon: mdi:cog
    entities:
      - input_number.library_temperature_off
      - input_number.library_temperature_cosy
      - input_number.library_temperature_bright
      - input_number.library_temperature_read
