- alias: "Calendar Jerome Scene"
  trigger:
    - platform: state
      entity_id: calendar.jerome_scene
      to: "on"
  action:
    - service_template: input_select.select_option
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "jerome" in l %}
          {%   set u = "bedroom_jerome" %}
          {% endif %}
          input_select.{{u}}_select
        option: >
          {% set v = trigger.to_state.attributes.message.lower().split()|last %}
          {{ v[0].upper() ~ v[1:].lower() }}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/jerome-scene'
        payload: '{{trigger.to_state.attributes.message}}'

- alias: "Calendar Jerome Climate"
  trigger:
    - platform: state
      entity_id: calendar.jerome_climate
      to: "on"
  action:
    - service_template: climate.set_temperature
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "jerome" in l %}
          {%   set u = "bedroom_jerome" %}
          {% endif %}
          group.{{u}}_thermostats
        temperature: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {{l|last|float}}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/jerome-climate'
        payload: '{{trigger.to_state.attributes.message}}'

