- alias: "Kitchen Mood"
  trigger:
    platform: state
    entity_id: input_select.kitchen_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.kitchen_select", "Off") %}
            scene.kitchen_off
          {%-elif is_state("input_select.kitchen_select", "Cosy") %}
            scene.kitchen_cosy
          {%-elif is_state("input_select.kitchen_select", "Bright") %}
            scene.kitchen_bright
          {% else %}
            None
          {% endif %}

