- alias: bedroom_mark_sleep_time
  trigger:
    - platform: time
      at: '03:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_mark_mode
        option: "Sleep"

- alias: bedroom_mark_off_time
  trigger:
    - platform: time
      at: '09:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_mark_mode
        option: "Off"
