homeassistant:
  customize:
    climate.bedroom_mark_thermostat:
      friendly_name: "Mark's Bedroom Heating"
    sensor.bedroom_mark_temperature:
      friendly_name: "Mark's Bedroom"
      icon: mdi:thermometer

group:
  g_debug_bedroom_mark_heating:
    entities:
      - climate.bedroom_mark_thermostat
      - climate.bedroom_mark_south_comfort_setpoint
      - climate.bedroom_mark_north_comfort_setpoint
      - switch.bedroom_mark_demand

  g_debug_bedroom_mark_temperature:
    entities:
      - sensor.bedroom_mark_temperature
      - sensor.bedroom_mark_south_current_temperature
      - sensor.bedroom_mark_north_current_temperature
      - sensor.bedroom_mark_south_temperature
      - sensor.bedroom_mark_north_temperature

  # Non-UI group which forwards setpoint updates
  #  Name is mapped from climate.foo_thermostat -> group.g_foo_thermostat
  g_bedroom_mark_thermostat:
    view: false
    entities:
      - climate.bedroom_mark_south_comfort_setpoint
      - climate.bedroom_mark_north_comfort_setpoint

climate:
  - name: bedroom_mark_thermostat
    platform: generic_thermostat
    heater: switch.bedroom_mark_demand
    target_sensor: sensor.bedroom_mark_temperature
    max_temp: 25
    min_temp: 5
    target_temp: 10.0

switch:
  - name: bedroom_mark_demand
    platform: mqtt
    command_topic: ha/bedroom-mark/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

sensor:
  - name: bedroom_mark_south_current_temperature
    platform: mqtt
    state_topic: 'ha/raw/sensor.bedroom_mark_south_temperature/state'
    ## dev: for mock mqtt devices
    #value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "\xB0C"
    expire_after: 10  # 1800  # 30mins
    force_update: true

  - name: bedroom_mark_north_current_temperature
    platform: mqtt
    state_topic: 'ha/raw/sensor.bedroom_mark_north_temperature/state'
    ## dev: for mock mqtt devices
    #value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "\xB0C"
    expire_after: 10  # 1800  # 30mins
    force_update: true

  - name: bedroom_mark_temperature
    platform: min_max
    type: max  # minimize occasional 0 readings. Replace with median?
    entity_ids:
      - sensor.bedroom_mark_south_current_temperature
      - sensor.bedroom_mark_north_current_temperature

automation:
  # Redirect received temperatures over mqtt
  - alias: "bedroom_mark_update_temperature"
    trigger:
      - platform: state
        entity_id: sensor.bedroom_mark_south_temperature
      - platform: state
        entity_id: sensor.bedroom_mark_north_temperature
    action:
      - service: mqtt.publish
        data_template:
          topic: 'ha/raw/{{trigger.entity_id}}/state'
          payload: '{{ trigger.to_state.state }}'

