homeassistant:
  customize:
    climate.bedroom_mark_thermostat:
      friendly_name: "Mark's Bedroom Heating"
    sensor.bedroom_mark_temperature:
      friendly_name: "Mark's Bedroom"
      icon: mdi:thermometer
      unit_of_measurement: "\xB0C"

    climate.bedroom_mark_south_thermostat:
      min_temp: 5
      max_temp: 25
    climate.bedroom_mark_north_thermostat:
      min_temp: 5
      max_temp: 25


group:
  g_debug_bedroom_mark_heating:
    entities:
      - climate.bedroom_mark_thermostat
      - climate.bedroom_mark_south_thermostat
      - climate.bedroom_mark_north_thermostat
      - switch.bedroom_mark_demand

  # Non-UI group which forwards setpoint updates
  #  Name is mapped from climate.foo_thermostat -> group.g_foo_thermostat
  g_bedroom_mark_thermostat:
    entities:
      - climate.bedroom_mark_south_thermostat
      - climate.bedroom_mark_north_thermostat

climate:
  - name: bedroom_mark_thermostat
    platform: generic_thermostat
    heater: switch.bedroom_mark_demand
    target_sensor: sensor.bedroom_mark_temperature
    max_temp: 25
    min_temp: 5
    target_temp: 10.0

switch:
  - name: bedroom_mark_demand
    platform: mqtt
    command_topic: ha/bedroom-mark/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

sensor:
  - name: bedroom_mark_south_current_temperature
    platform: mqtt
    state_topic: 'zwave/bedroom_mark_south/49/0/Air_temperature'
    value_template: '{{ value_json.value }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: bedroom_mark_north_current_temperature
    platform: mqtt
    state_topic: 'zwave/bedroom_mark_north/49/0/Air_temperature'
    value_template: '{{ value_json.value }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: bedroom_mark_temperature
    platform: min_max
    type: max  # minimize occasional 0 readings. Replace with median?
    entity_ids:
      - sensor.aeotec_zw100_multisensor_temperature_air
      - sensor.bedroom_mark_south_current_temperature
      - sensor.bedroom_mark_north_current_temperature

  - platform: template
    sensors:
      bedroom_mark_setpoint:
        value_template: "{{ states.climate.bedroom_mark_thermostat.attributes.temperature }}"
        unit_of_measurement: "\xB0C"
