#
# Bedroom Mark
#

homeassistant:
  customize:
    group.bedroom_mark_lights:
      icon: mdi:lightbulb-on

    light.bedroom_mark_overhead_instance_1_level:
      friendly_name: "Overhead"
      icon: mdi:ceiling-light
    light.bedroom_mark_lamp:
      friendly_name: "Dressing Table"

group:
  # floorplan
  bedroom_mark_compact_ui:
    name: "Mark's Bedroom"
    entities:
    - input_select.bedroom_mark_mode
    - climate.bedroom_mark_thermostat
    - group.bedroom_mark_lights
    - media_player.bedroom_mark

  bedroom_mark_setpoints:
    name: "Mark's Bedroom Setpoints"
    entities:
    - climate.bedroom_mark_south_mode
    - climate.bedroom_mark_north_mode

  bedroom_mark_lights:
    name: "Mark's Bedroom Lights"
    entities:
    - light.bedroom_mark_overhead_instance_1_level
    - light.bedroom_mark_lamp

  bedroom_mark_appliances:
    name: "Mark's Bedroom Appliances"
    entities:

  bedroom_mark_media_players:
    entities:
    - media_player.bedroom_mark

scene:
  - name: bedroom_mark_off
    entities:
      group.bedroom_mark_lights:
        state: off
      switch.bedroom_mark_appliances:
        state: off
      media_player.bedroom_mark:
        state: paused
      media_player.snapcast_client_bedroommark:
        state: on
        is_volume_muted: true

  - name: bedroom_mark_sleep
    entities:
      group.bedroom_mark_lights:
        state: off

  - name: bedroom_mark_play
    entities:
      group.bedroom_mark_lights:
        state: on

light:
  - platform: switch
    name: bedroom_mark_lamp
    entity_id: switch.lightwaverf_siemens_f15c72_1


switch:
  # Now for supporting mock thermostats only.
  #  Remove when mock thermostats move to mqtt hvac
  - name: bedroom_mark_south_demand
    platform: mqtt
    command_topic: ha/bedroom-mark/south/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

  - name: bedroom_mark_north_demand
    platform: mqtt
    command_topic: ha/bedroom-mark/north/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
