homeassistant:
  customize:
    climate.hall_thermostat:
      friendly_name: "Hall Heating"
    sensor.hall_temperature:
      friendly_name: "Hall"
      icon: mdi:thermometer
      unit_of_measurement: "\xB0C"

group:
  g_debug_hall_heating:
    entities:
      - climate.hall_thermostat
      - climate.hall_east_thermostat
      - climate.hall_west_thermostat
      - switch.hall_demand

  # Non-UI group which forwards setpoint updates
  #  Name is mapped from climate.foo_thermostat -> group.g_foo_thermostat
  g_hall_thermostat:
    entities:
      - climate.hall_east_thermostat
      - climate.hall_west_thermostat

climate:
  - name: hall_thermostat
    platform: generic_thermostat
    heater: switch.hall_demand
    target_sensor: sensor.hall_temperature
    max_temp: 25
    min_temp: 5
    target_temp: 10.0

switch:
  - name: hall_demand
    platform: mqtt
    command_topic: ha/hall/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

sensor:
  - name: main_heating_thermostat_air_temperature
    platform: mqtt
    state_topic: 'zwave/main_heating_thermostat/49/0/Air_temperature'
    value_template: '{{ value_json.value }}'
    unit_of_measurement: "\xB0C"
    force_update: true

  - name: hall_east_current_temperature
    platform: mqtt
    state_topic: 'zwave/hall_east/49/0/Air_temperature'
    value_template: '{{ value_json.value }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: hall_west_current_temperature
    platform: mqtt
    state_topic: 'zwave/hall_west/49/0/Air_temperature'
    value_template: '{{ value_json.value }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: hall_temperature
    platform: min_max
    type: max  # minimize occasional 0 readings. Replace with median?
    entity_ids:
      - sensor.hall_east_current_temperature
      - sensor.hall_west_current_temperature
      - sensor.main_heating_thermostat_air_temperature
