homeassistant: !include homeassistant.yaml
group: !include groups.yaml
#climate: !include climate.yaml
#input_select: !include input_select.yaml
#scene: !include scenes.yaml
script: !include_dir_merge_named scripts
sensor: !include sensors.yaml
switch: !include switches.yaml
#automation: !include_dir_merge_list automations
