#
# Hall
#

homeassistant:
  customize:
    sensor.hall_west_temperature:
      friendly_name: Hall West
    sensor.hall_east_temperature:
      friendly_name: Hall East
    sensor.annex_hall_temperature:
      friendly_name: Annex Hall
    sensor.hall_west_battery:
      friendly_name: Hall West Battery
      icon: mdi:battery
    sensor.hall_east_battery:
      friendly_name: Hall East Battery
      icon: mdi:battery
    sensor.annex_hall_battery:
      friendly_name: Annex Hall Battery
      icon: mdi:battery

    climate.hall_west_thermostat:
      friendly_name: Hall West
    climate.hall_east_thermostat:
      friendly_name: Hall East
    climate.annex_hall_thermostat:
      friendly_name: Annex Hall

    climate.hall_west_mode:
      min_temp: 5
      max_temp: 25
    climate.hall_east_mode:
      min_temp: 5
      max_temp: 25
    climate.annex_hall_mode:
      min_temp: 5
      max_temp: 25

    # FIXME: media-control card ignores 'name' settings
    media_player.outside_amplifier:
      friendly_name: Outside Amplifier

group:
  hall_compact_ui:
    name: Hall
    icon: mdi:fullscreen-exit
    entities:
    - climate.hall_thermostat
    - climate.annex_hall_thermostat
    - group.hall_lights

  hall_setpoints:
    name: Hall Setpoints
    entities:
    - climate.hall_west_mode
    - climate.hall_east_mode
    - climate.annex_hall_mode

  hall_lights:
    name: Hall Lights

#scene:

sensor:
  - platform: template
    sensors:
      hall_east_battery:
        value_template: >
          {% if states.zwave.hall_east %}
            {{ states.zwave.hall_east.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: '%'
        entity_id: zwave.hall_east

      hall_west_battery:
        value_template: >
          {% if states.zwave.hall_west %}
            {{ states.zwave.hall_west.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: '%'
        entity_id: zwave.hall_west

      annex_hall_battery:
        value_template: >
          {% if states.zwave.annex_hall %}
            {{ states.zwave.annex_hall.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: '%'
        entity_id: zwave.annex_hall

switch:
  # Now for supporting mock thermostats only.
  #  Remove when mock thermostats move to mqtt hvac
  - name: hall_west_demand
    platform: mqtt
    command_topic: ha/hall/west/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

  - name: hall_east_demand
    platform: mqtt
    command_topic: ha/hall/east/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

media_player:
  - name: Outside Amplifier
    platform: onkyo
    host: utility-amp
    sources:
      #dvd: 'BD/DVD'
      video1: 'Media' # STB/DVR
      #video2: 'CBL/SAT' # Cable/SAT
      #video3: 'Game'
      #video6: 'PC' # PC
      #aux1: 'Ext Aux'
      cd: 'Kitchen Media'
      phono: 'Aux'
      fm: 'FM' # -> needs onkyo fix
      am: 'AM' # -> needs onkyo fix
      network: 'Network'
      usb: 'USB'

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
