#
# Hall
#

homeassistant:
  customize:
    climate.hall_west_thermostat:
      min_temp: 5
      max_temp: 25
    climate.hall_east_thermostat:
      min_temp: 5
      max_temp: 25
    climate.annex_hall_west_thermostat:
      min_temp: 5
      max_temp: 25

group:
  hall_compact_ui:
    name: Hall
    icon: mdi:fullscreen-exit
    entities:
    - climate.hall_thermostat
    - climate.annex_hall_thermostat
    - group.hall_lights

  hall_setpoints:
    name: Hall Setpoints
    entities:
    - climate.hall_west_thermostat
    - climate.hall_east_thermostat
    - climate.annex_hall_west_thermostat

  hall_lights:
    name: Hall Lights

#scene:

switch:
  # Now for supporting mock thermostats only.
  #  Remove when mock thermostats move to mqtt hvac
  - name: hall_west_demand
    platform: mqtt
    command_topic: ha/hall/west/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

  - name: hall_east_demand
    platform: mqtt
    command_topic: ha/hall/east/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
