#
# Hall
#

homeassistant:
  customize:
    sensor.hall_west_air_temperature:
      friendly_name: Hall West
    sensor.hall_east_air_temperature:
      friendly_name: Hall East
    sensor.annex_hall_west_air_temperature:
      friendly_name: Annex Hall

    climate.hall_west_mode:
      min_temp: 5
      max_temp: 25
    climate.hall_east_mode:
      min_temp: 5
      max_temp: 25
    climate.annex_hall_west_mode:
      min_temp: 5
      max_temp: 25

    # FIXME: media-control card ignores 'name' settings
    media_player.outside_amplifier:
      friendly_name: Outside Amplifier

group:
  hall_compact_ui:
    name: Hall
    icon: mdi:fullscreen-exit
    entities:
    - climate.hall_thermostat
    - climate.annex_hall_thermostat
    - group.hall_lights

  hall_setpoints:
    name: Hall Setpoints
    entities:
    - climate.hall_west_mode
    - climate.hall_east_mode
    - climate.annex_hall_west_mode

  hall_lights:
    name: Hall Lights

#scene:

switch:
  # Now for supporting mock thermostats only.
  #  Remove when mock thermostats move to mqtt hvac
  - name: hall_west_demand
    platform: mqtt
    command_topic: ha/hall/west/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

  - name: hall_east_demand
    platform: mqtt
    command_topic: ha/hall/east/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

media_player:
  - name: Outside Amplifier
    platform: onkyo
    host: utility-amp
    sources:
      #dvd: 'BD/DVD'
      video1: 'Media' # STB/DVR
      #video2: 'CBL/SAT' # Cable/SAT
      #video3: 'Game'
      #video6: 'PC' # PC
      #aux1: 'Ext Aux'
      cd: 'Kitchen Media'
      phono: 'Aux'
      fm: 'FM' # -> needs onkyo fix
      am: 'AM' # -> needs onkyo fix
      network: 'Network'
      usb: 'USB'

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
