- platform: template
  sensors:
    main_heating_thermostat_battery:
      value_template: >
        {% if states.sensor.horstmann_scsc17_thermostat_temperature_35_1 %}
          {{ states.sensor.horstmann_scsc17_thermostat_temperature_35_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    annex_heating_thermostat_battery:
      value_template: >
        {% if states.sensor.horstmann_scsc17_thermostat_temperature_50_1 %}
          {{ states.sensor.horstmann_scsc17_thermostat_temperature_50_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_multisensor_battery:
      value_template: >
        {% if states.sensor.aeotec_dsb05_multisensor_temperature_3_1 %}
          {{ states.sensor.aeotec_dsb05_multisensor_temperature_3_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_east_battery:
      value_template: >
        {% if states.sensor.hall_east_temperature_24_1 %}
          {{ states.sensor.hall_east_temperature_24_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_west_battery:
      value_template: >
        {% if states.sensor.hall_west_temperature_13_1 %}
          {{ states.sensor.hall_west_temperature_13_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    annex_hall_battery:
      value_template: >
        {% if states.sensor.annex_hall_temperature_43_1 %}
          {{ states.sensor.annex_hall_temperature_43_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    ballroom_east_battery:
      value_template: >
        {% if states.sensor.ballroom_east_temperature_33_1 %}
          {{ states.sensor.ballroom_east_temperature_33_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    bedroom_mark_battery:
      value_template: >
        {% if states.sensor.bedroom_mark_temperature_29_1 %}
          {{ states.sensor.bedroom_mark_temperature_29_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    kitchen_battery:
      value_template: >
        {% if states.sensor.kitchen_temperature_34_1 %}
          {{ states.sensor.kitchen_temperature_34_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    library_battery:
      value_template: >
        {% if states.sensor.library_temperature_25_1 %}
          {{ states.sensor.library_temperature_25_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    lounge_east_battery:
      value_template: >
        {% if states.sensor.lounge_east_temperature_30_1 %}
          {{ states.sensor.lounge_east_temperature_30_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    study_east_battery:
      value_template: >
        {% if states.sensor.study_east_temperature_14_1 %}
          {{ states.sensor.study_east_temperature_14_1.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    study_west_battery:
      value_template: >
        {% if states.sensor.study_west_temperature_15_1 %}
          {{ states.sensor.study_west_temperature_15_1.attributes.battery_level}}
        {%  else %}
          unknown
        {%  endif %}
      unit_of_measurement: '%'
