- platform: template
  sensors:
    main_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.main_heating_thermostat %}
          {{ states.zwave.main_heating_thermostat.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    annex_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.horstmann_scsc17_thermostat_50 %}
          {{ states.zwave.horstmann_scsc17_thermostat_50.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_multisensor_battery:
      value_template: >
        {% if states.zwave.aeotec_dsb05_multisensor_3 %}
          {{ states.zwave.aeotec_dsb05_multisensor_3.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_east_battery:
      value_template: >
        {% if states.zwave.hall_east_24 %}
          {{ states.zwave.hall_east_24.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_west_battery:
      value_template: >
        {% if states.zwave.hall_west_13 %}
          {{ states.zwave.hall_west_13.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    annex_hall_battery:
      value_template: >
        {% if states.zwave.annex_hall_43 %}
          {{ states.zwave.annex_hall_43.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    ballroom_east_battery:
      value_template: >
        {% if states.zwave.ballroom_east_33 %}
          {{ states.zwave.ballroom_east_33.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    bedroom_mark_battery:
      value_template: >
        {% if states.zwave.bedroom_mark_29 %}
          {{ states.zwave.bedroom_mark_29.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    kitchen_battery:
      value_template: >
        {% if states.zwave.kitchen_34 %}
          {{ states.zwave.kitchen_34.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    library_battery:
      value_template: >
        {% if states.zwave.library_25 %}
          {{ states.zwave.library_25.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    lounge_east_battery:
      value_template: >
        {% if states.zwave.lounge_east_30 %}
          {{ states.zwave.lounge_east_30.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    study_east_battery:
      value_template: >
        {% if states.zwave.study_east_14 %}
          {{ states.zwave.study_east_14.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    study_west_battery:
      value_template: >
        {% if states.zwave.study_west_15 %}
          {{ states.zwave.study_west_15.attributes.battery_level}}
        {%  else %}
          unknown
        {%  endif %}
      unit_of_measurement: '%'
    bedroom_jerome_battery:
      value_template: >
        {% if states.zwave.bedroom_jerome_44 %}
          {{ states.zwave.bedroom_jerome_44.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    bedroom_ros_battery:
      value_template: >
        {% if states.zwave.bedroom_ros_55 %}
          {{ states.zwave.bedroom_ros_55.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
