- platform: template
  sensors:
    main_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.main_heating_thermostat %}
          {{ states.zwave.main_heating_thermostat.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    annex_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.annex_heating_thermostat %}
          {{ states.zwave.annex_heating_thermostat.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_multisensor_battery:
      value_template: >
        {% if states.zwave.aeotec_dsb05_multisensor %}
          {{ states.zwave.aeotec_dsb05_multisensor.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_east_battery:
      value_template: >
        {% if states.zwave.hall_east %}
          {{ states.zwave.hall_east.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_west_battery:
      value_template: >
        {% if states.zwave.hall_west %}
          {{ states.zwave.hall_west.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    annex_hall_battery:
      value_template: >
        {% if states.zwave.annex_hall %}
          {{ states.zwave.annex_hall.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    ballroom_east_battery:
      value_template: >
        {% if states.zwave.ballroom_east %}
          {{ states.zwave.ballroom_east.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    bedroom_mark_battery:
      value_template: >
        {% if states.zwave.bedroom_mark %}
          {{ states.zwave.bedroom_mark.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    library_battery:
      value_template: >
        {% if states.zwave.library %}
          {{ states.zwave.library.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    lounge_east_battery:
      value_template: >
        {% if states.zwave.lounge_east %}
          {{ states.zwave.lounge_east.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    study_east_battery:
      value_template: >
        {% if states.zwave.study_east %}
          {{ states.zwave.study_east.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    study_west_battery:
      value_template: >
        {% if states.zwave.study_west %}
          {{ states.zwave.study_west.attributes.battery_level}}
        {%  else %}
          unknown
        {%  endif %}
      unit_of_measurement: '%'
    bedroom_jerome_battery:
      value_template: >
        {% if states.zwave.bedroom_jerome %}
          {{ states.zwave.bedroom_jerome.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    bedroom_ros_battery:
      value_template: >
        {% if states.zwave.bedroom_ros %}
          {{ states.zwave.bedroom_ros.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
