- platform: template
  sensors:
    main_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.main_heating_thermostat %}
          {{ states.zwave.main_heating_thermostat.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
      entity_id: zwave.main_heating_thermostat

    annex_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.annex_heating_thermostat %}
          {{ states.zwave.annex_heating_thermostat.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
      entity_id: zwave.annex_heating_thermostat
