- platform: template
  sensors:
    main_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.main_heating_thermostat %}
          {{ states.zwave.main_heating_thermostat.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    annex_heating_thermostat_battery:
      value_template: >
        {% if states.zwave.annex_heating_thermostat %}
          {{ states.zwave.annex_heating_thermostat.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    hall_multisensor_battery:
      value_template: >
        {% if states.zwave.aeotec_dsb05_multisensor %}
          {{ states.zwave.aeotec_dsb05_multisensor.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
