- platform: template
  sensors:
    main_heating_thermostat_battery:
      value_template: '{{ states.sensor.horstmann_scsc17_thermostat_temperature_35.battery_level }}'
      unit_of_measurement: '%'
    annex_heating_thermostat_battery:
      value_template: '{{ states.sensor.horstmann_scsc17_thermostat_temperature_50.battery_level }}'
      unit_of_measurement: '%'
    hall_multisensor_battery:
      value_template: '{{ states.sensor.aeotec_dsb05_multisensor_temperature_3.battery_level }}'
      unit_of_measurement: '%'
    hall_east_battery:
      value_template: '{{ states.sensor.hall_east_temperature_24.battery_level }}'
      unit_of_measurement: '%'
    hall_west_battery:
      value_template: '{{ states.sensor.hall_west_temperature_13.battery_level }}'
      unit_of_measurement: '%'
    hall_annex_battery:
      value_template: '{{ states.sensor.annex_hall_temperature_43.battery_level }}'
      unit_of_measurement: '%'
    ballroom_east_battery:
      value_template: '{{ states.sensor.ballroom_east_temperature_33.battery_level }}'
      unit_of_measurement: '%'
    bedroom_mark_battery:
      value_template: '{{ states.sensor.bedroom_mark_temperature_29.battery_level }}'
      unit_of_measurement: '%'
    kitchen_battery:
      value_template: '{{ states.sensor.kitchen_temperature_34.battery_level }}'
      unit_of_measurement: '%'
    library_battery:
      value_template: '{{ states.sensor.library_temperature_25.battery_level }}'
      unit_of_measurement: '%'
    lounge_battery:
      value_template: '{{ states.sensor.lounge_east_temperature_30.battery_level }}'
      unit_of_measurement: '%'
    study_east_battery:
      value_template: '{{ states.sensor.study_east_temperature_14.battery_level }}'
      unit_of_measurement: '%'
    study_west_battery:
      value_template: '{{ states.sensor.study_west_temperature_15.battery_level }}'
      unit_of_measurement: '%'
