#
# Dim lights based on media player status
#

homeassistant:
  customize:
    group.g_study_media_dimming:
      icon: mdi:brightness-auto
    input_boolean.study_dim_for_movie:
      icon: mdi:movie
    input_boolean.study_dim_for_tv:
      icon: mdi:television-classic
    input_number.study_media_dimmer_level:
      icon: mdi:brightness-6

    package.study_media_dimming: &study_dim_condition
      condition:
        condition: and
        conditions:
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
          - condition: state
            entity_id: group.study_lights
            state: "on"
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.study_dim_for_movie
                    state: "on"
                  - condition: template
                    value_template: >
                      {{ trigger.to_state.attributes.media_content_type == "movie" }}
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.study_dim_for_tv
                    state: "on"
                  - condition: template
                    value_template: >
                      {{ trigger.to_state.attributes.media_content_type == "tvshow" }}

group:
  g_study_media_dimming:
    name: Media Auto Dim
    entities:
      - input_boolean.study_dim_for_movie
      - input_boolean.study_dim_for_tv
      - input_number.study_media_dimmer_level

input_boolean:
  study_dim_for_tv:
    name: Dim during TV shows
  study_dim_for_movie:
    name: Dim during Movies

input_number:
  study_media_dimmer_level:
    name: "Dim Level"
    min: 0
    max: 40
    step: 5

automation:
  - alias: "Study Dim on Media Playing"
    trigger:
      - platform: state
        entity_id: media_player.study_kodi
        to: "playing"
        for:
          seconds: 2
    <<: *study_dim_condition
    action:
      - service: light.turn_on
        data_template:
          entity_id: group.study_lights
          brightness_pct: "{{ states.input_number.study_media_dimmer_level.state | int }}"
          transition: "2"

  - alias: "Study Dim on Media Paused"
    trigger:
      - platform: state
        entity_id: media_player.study_kodi
        to: "paused"
    <<: *study_dim_condition
    action:
      service: light.turn_on
      data:
        entity_id: group.study_lights
        brightness_pct: "50"
        transition: "3"

  - alias: "Study Dim on Media Stopped"
    trigger:
      - platform: state
        entity_id: media_player.study_kodi
        from: "playing"
        to: "idle"
    <<: *study_dim_condition
    action:
      service: scene.turn_on
      entity_id: scene.study_bright
