#
# Mode selection
#
# Stores last user intent.
# Reverts to manual when user adjustments are made.
#

input_select:
  study_mode:
    name: Study Mode
    options:
      - 'Off'
      - 'Cosy'
      - 'Bright'
      - 'Work'
      - 'Manual'
    initial: 'Off'
    icon: mdi:printer

input_number:
  study_temperature_off:
    name: 'Off Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 10
    step: 1

  study_temperature_cosy:
    name: 'Cosy Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 22
    step: 1

  study_temperature_bright:
    name: 'Bright Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 20
    step: 1

  study_temperature_work:
    name: 'Work Temp'
    icon: mdi:thermostat
    unit_of_measurement: "\xB0C"
    min: 5
    max: 25
    initial: 20
    step: 1

automation:
  - alias: study_revert_to_manual
    trigger:
      - platform: state
        entity_id:
          - group.study_lights
          - sensor.study_setpoint
    #condition:
    #  condition: template  # otherwise we reset on all state updates
    #  value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
        - service: input_select.select_option
          data:
            entity_id: input_select.study_mode
            option: 'Manual'


  - alias: study_mode
    trigger:
      - platform: state
        entity_id: input_select.study_mode
    action:
      - service: script.set_mode
        data_template:
          room: 'study'
          mode: '{{ trigger.to_state.state | lower }}'
