#
# Study
#

homeassistant:
  customize:
    climate.study_east_mode:
      min_temp: 5
      max_temp: 25
    climate.study_west_mode:
      min_temp: 5
      max_temp: 25

group:
  # floorplan
  study_compact_ui:
    name: Study
    entities:
    - input_select.study_mode
    - climate.study_thermostat
    - group.study_lights

  study_setpoints:
    name: Study Setpoints
    entities:
    - climate.study_east_mode
    - climate.study_west_mode

  study_lights:
    name: Study Lights
    entities: {}

  study_appliances:
    name: Study Appliances
    entities:
    - device_tracker.ricoh213w
    - device_tracker.canonmg5550

scene:
  - name: study_off
    entities:
      group.study_lights:
        state: off
      media_player.study:
        state: paused
      media_player.snapcast_client_study:
        state: on
        is_volume_muted: true

  - name: study_cosy
    entities:
      group.study_lights:
        state: on
        brightness_pct: 20

  - name: study_bright
    entities:
      group.study_lights:
        state: on
        brightness_pct: 100

  - name: study_work
    entities:
      group.study_lights:
        state: on
        brightness_pct: 100
switch:
  # Now for supporting mock thermostats only.
  #  Remove when mock thermostats move to mqtt hvac
  - name: study_west_demand
    platform: mqtt
    command_topic: ha/study/west/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

  - name: study_east_demand
    platform: mqtt
    command_topic: ha/study/east/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

media_player:
  - name: study
    platform: kodi
    host: study.home.whalebarn.com
    port: 80

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts

