- platform: template
  sensors:
    study_east_battery:
      value_template: >
        {% if states.zwave.study_east %}
          {{ states.zwave.study_east.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
    study_west_battery:
      value_template: >
        {% if states.zwave.study_west %}
          {{ states.zwave.study_west.attributes.battery_level}}
        {%  else %}
          unknown
        {%  endif %}
      unit_of_measurement: '%'

