#
# Guest Room
#

homeassistant:
  customize:
    climate.guest_room_north_thermostat:
      min_temp: 8
      max_temp: 25

group:
  # floorplan
  guest_room_compact_ui:
    name: Guest Room
    icon: mdi:hotel
    entities:
    - input_select.guest_room_mode
    - climate.guest_room_thermostat
    - group.guest_room_lights

  guest_room_setpoints:
    name: Guest Room Setpoints
    entities:
    - climate.guest_room_north_thermostat

  guest_room_lights:
    name: Guest Room Lights

scene:
  - name: guest_room_off
    entities:
      group.guest_room_lights:
        state: off

  - name: guest_room_sleep
    entities:
      group.guest_room_lights:
        state: off

  - name: guest_room_cosy
    entities:
      group.guest_room_lights:
        state: on

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
