- platform: template
  sensors:
    guest_room_battery:
      value_template: >
        {% if states.zwave.guest_room %}
          {{ states.zwave.guest_room.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
