group:
  g_guest_room_settings_ui:
    name: Settings
    icon: mdi:cog
    entities:
      - input_number.guest_room_temperature_off
      - input_number.guest_room_temperature_cosy
      - input_number.guest_room_temperature_sleep
      - automation.guest_room_set_real_thermostats


