- alias: "Library Mood"
  trigger:
    platform: state
    entity_id: input_select.library_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.library_select", "Off") %}
            scene.library_off
          {%-elif is_state("input_select.library_select", "Chat") %}
            scene.library_chat
          {%-elif is_state("input_select.library_select", "Read") %}
            scene.library_read
          {% else %}
            None
          {% endif %}

