#
# Mode selection
#
# Stores last user intent.
# Reverts to manual when user adjustments are made.
#

homeassistant:
  customize:
    input_select.bedroom_main3_mode:
      icon: mdi:bed-empty

input_select:
  bedroom_main3_mode:
    options:
      - 'Off'
      - 'Cosy'
      - 'Sleep'
      - 'Manual'
    initial: 'Off'

input_number:
  bedroom_main3_temperature_off:
    name: 'Off Temp'
    initial: 10
    <<: &bedroom_main3_temp_defaults
      icon: mdi:thermostat
      unit_of_measurement: "\xB0C"
      min: 8
      max: 25
      step: 1

  bedroom_main3_temperature_cosy:
    name: 'Cosy Temp'
    initial: 20
    <<: *bedroom_main3_temp_defaults

  bedroom_main3_temperature_sleep:
    name: 'Sleep Temp'
    initial: 15
    <<: *bedroom_main3_temp_defaults

automation:
  - alias: bedroom_main3_revert_to_manual
    trigger:
      - platform: state
        entity_id:
          - group.bedroom_main3_lights
          - sensor.bedroom_main3_setpoint
    #condition:
    #  condition: template  # otherwise we reset on all state updates
    #  value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
        - service: input_select.select_option
          data:
            entity_id: input_select.bedroom_main3_mode
            option: 'Manual'


  - alias: bedroom_main3_mode
    trigger:
      - platform: state
        entity_id: input_select.bedroom_main3_mode
    action:
      - service: script.set_mode
        data_template:
          room: 'bedroom_main3'
          mode: '{{ trigger.to_state.state | lower }}'
