#
# Tom's Room
#

homeassistant:
  customize:
    sensor.bedroom_main3_battery_level:
      icon: mdi:battery
    climate.bedroom_main3_east_mode:
      min_temp: 8
      max_temp: 25

group:
  # floorplan
  bedroom_main3_compact_ui:
    name: "Elle's Bedroom"
    entities:
    - input_select.bedroom_main3_mode
    - climate.bedroom_main3_thermostat
    - group.bedroom_main3_lights

  bedroom_main3_setpoints:
    entities:
    - climate.bedroom_main3_east_mode

  bedroom_main3_lights:


scene:
  - name: bedroom_main3_off
    entities:
      group.bedroom_main3_lights:
        state: off
      switch.bedroom_main3_appliances:
        state: off

  - name: bedroom_main3_sleep
    entities:
      group.bedroom_main3_lights:
        state: off

  - name: bedroom_main3_cosy
    entities:
      group.bedroom_main3_lights:
        state: on

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
