group:
  g_bedroom_main3_settings_ui:
    name: Settings
    icon: mdi:settings
    control: hidden
    entities:
      - input_number.bedroom_main3_temperature_off
      - input_number.bedroom_main3_temperature_cosy
      - input_number.bedroom_main3_temperature_sleep


