# Repeat the command every 20 minutes to avoid failsafe mode.
- alias: "Annex Heating Poll On"
  trigger:
    - platform: time_pattern
      minutes: '/20'
      seconds: 12
  condition:
    - condition: state
      entity_id: group.annex_heating_demand
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.annex_heating_relay_switch

- alias: "Annex Heating Poll Off"
  trigger:
    - platform: time_pattern
      minutes: '/20'
      seconds: 14
  condition:
    - condition: state
      entity_id: group.annex_heating_demand
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.annex_heating_relay_switch
