- alias: "Mark's Bedroom Sleep Time"
  trigger:
    - platform: time
      after: '03:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.marks_bedroom_select
        option: "Sleep"

