- alias: "Calendar Service"
  trigger:
    - platform: state
      entity_id: calendar.service
  action:
    - service_template: '{{ trigger.to_state.attributes.message.split()[1] }}'
      data_template:
        entity_id: '{{ trigger.to_state.attributes.message.split()[2] }}'
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/service'
        payload: '{"service":"{{trigger.to_state.attributes.message.split()[1]}}","data":"{{trigger.to_state.attributes.message.split()[2]}}"}'

- alias: "Calendar Scene"
  trigger:
    - platform: state
      entity_id: calendar.scene
      to: "on"
    - platform: state
      entity_id: calendar.mark_scene
      to: "on"
    - platform: state
      entity_id: calendar.jerome_scene
      to: "on"
    - platform: state
      entity_id: calendar.ros_scene
      to: "on"
  action:
    - service_template: input_select.select_option
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "mark" in l %}
          {%   set u = "bedroom_mark" %}
          {% elif "jerome" in l %}
          {%   set u = "bedroom_jerome" %}
          {% elif "ros" in l %}
          {%   set u = "bedroom_ros" %}
          {% endif %}
          input_select.{{u}}_select
        option: >
          {% set v = trigger.to_state.attributes.message.lower().split()|last %}
          {{ v[0].upper() ~ v[1:].lower() }}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/scene'
        payload: '{{trigger.to_state.attributes.message}}'

- alias: "Calendar Climate"
  trigger:
    - platform: state
      entity_id: calendar.climate
      to: "on"
  action:
    - service_template: climate.set_temperature
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "mark" in l %}
          {%   set u = "bedroom_mark" %}
          {% elif "jerome" in l %}
          {%   set u = "bedroom_jerome" %}
          {% elif "ros" in l %}
          {%   set u = "bedroom_ros" %}
          {% endif %}
          climate.{{u}}_thermostat
        temperature: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {{l|last|float}}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/climate'
        payload: '{{trigger.to_state.attributes.message}}'

- alias: "Calendar Bin"
  trigger:
    - platform: state
      entity_id: calendar.bin
      to: "on"
  action:
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/bin'
        payload: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{l}}
    - service: notify.whalebarn
      data_template:
        message: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{"Bin Day: "+l}}
    - service: persistent_notification.create
      data_template:
        title: 'Bin Day'
        message: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{"Bin Day: "+l}}
        notification_id: 'bin-day'

- alias: "Calendar Oil"
  trigger:
    - platform: state
      entity_id: calendar.oil
      to: "on"
  action:
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/oil'
        payload: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{l}}
    - service: notify.whalebarn
      data_template:
        message: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{"Oil Check: "+l}}
    - service: persistent_notification.create
      data_template:
        title: 'Oil Check'
        message: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{"Oil Day: "+l}}
        notification_id: 'oil-check'

