- alias: "Calendar Service"
  trigger:
    - platform: state
      entity_id: calendar.service
  action:
    - service_template: '{{ trigger.to_state.attributes.message.split()[1] }}'
      data_template:
        entity_id: '{{ trigger.to_state.attributes.message.split()[2] }}'
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/service'
        payload: '{"service":"{{trigger.to_state.attributes.message.split()[1]}}","data":"{{trigger.to_state.attributes.message.split()[2]}}"}'

- alias: "Calendar Scene"
  trigger:
    - platform: state
      entity_id: calendar.scene
      to: "on"
  action:
    - service_template: input_select.select_option
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "study" in l %}
          {%   set u = "study" %}
          {% elif "kitchen" in l %}
          {%   set u = "kitchen" %}
          {% elif "lounge" in l or "sitting" in l or "sittingroom" in l %}
          {%   set u = "lounge" %}
          {% elif "library" in l %}
          {%   set u = "library" %}
          {% elif "ballroom" in l or "ball" in l %}
          {%   set u = "ballroom" %}
          ## hall and annex_hall don't have mode settings
          #{% elif "hall" in l or "hallway" in l %}
          #{%   set u = "hall" %}
          #{% elif "annex" in l or "annex_hall" in l or "annexhall" in l %}
          #{%   set u = "annex_hall" %}
          {% elif "guestroom" in l or "guest" in l %}
          {%   set u = "guest_room" %}
          {% elif "bedroom_annex2" in l or "annex2" in l or ("annex" in l and "bedroom2" in l) %}
          {%   set u = "bedroom_annex2" %}
          {% endif %}
          input_select.{{u}}_mode
        option: >
          {% set v = trigger.to_state.attributes.message.lower().split()|last %}
          {{ v[0].upper() ~ v[1:].lower() }}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/scene'
        payload: '{{trigger.to_state.attributes.message}}'

- alias: "Calendar Climate"
  trigger:
    - platform: state
      entity_id: calendar.climate
      to: "on"
  action:
    - service_template: climate.set_temperature
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "study" in l %}
          {%   set u = "study" %}
          {% elif "kitchen" in l %}
          {%   set u = "kitchen" %}
          {% elif "lounge" in l or "sitting" in l or "sittingroom" in l %}
          {%   set u = "lounge" %}
          {% elif "library" in l %}
          {%   set u = "library" %}
          {% elif "ballroom" in l or "ball" in l %}
          {%   set u = "ballroom" %}
          {% elif "hall" in l or "hallway" in l %}
          {%   set u = "hall" %}
          {% elif "annex" in l or "annex_hall" in l or "annexhall" in l %}
          {%   set u = "annex_hall" %}
          {% elif "guestroom" in l or "guest" in l %}
          {%   set u = "guest_room" %}
          {% elif "bedroom_main2" in l or "main2" in l or ("main" in l and "bedroom2" in l) %}
          {%   set u = "bedroom_main2" %}
          {% elif "bedroom_main3" in l or "main3" in l or ("main" in l and "bedroom3" in l) %}
          {%   set u = "bedroom_main3" %}
          {% elif "bedroom_annex2" in l or "annex2" in l or ("annex" in l and "bedroom2" in l) %}
          {%   set u = "bedroom_annex2" %}
          {% endif %}
          climate.{{u}}_thermostat
        temperature: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {{l|last|float}}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/climate'
        payload: '{{trigger.to_state.attributes.message}}'

# Trigger a Bin notification with an offset of <some> hours before the start time.
# Cannot trigger on calendar state because of this so trigger every hour but
# guard with a condition.
#
# One notification for any or all bins.
#
- alias: "Calendar Bin"
  trigger:
    # Every hour at 5 mins past
    - platform: time_pattern
      minutes: "5"
  variables:
    # notify only between now+11h30m to now+12h00m
    in_12h00m: "{{ now().timestamp() + 1*60*60 }}"
    in_11h30m: "{{ in_12h00m - 0.5*60*60 }}"
    is_black: "{{ in_12h00m >= (states.calendar.black_bin.attributes.start_time | as_timestamp) > in_11h30m }}"
    is_blue: "{{ in_12h00m >= (states.calendar.blue_bin.attributes.start_time | as_timestamp) > in_11h30m }}"
    is_green: "{{ in_12h00m >= (states.calendar.green_bin.attributes.start_time | as_timestamp) > in_11h30m }}"
    event_title: >
      {{ 'Bins Tomorrow: ' + ["Black" if is_black, "Blue" if is_blue, "Green" if is_green]|select('defined')|join(', ') }}
  condition: >
    {{ is_black or is_blue or is_green }}
  action:
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/bin'
        payload: "{{event_title}}"
    - service: notify.whalebarn
      data_template:
        message: "{{event_title}}"
    - service: persistent_notification.create
      data_template:
        title: 'Bin Day'
        message: "{{event_title}}"
        notification_id: 'bin-day'
- alias: "Calendar Oil"
  trigger:
    - platform: state
      entity_id: calendar.oil
      to: "on"
  action:
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/oil'
        payload: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{l}}
    - service: notify.whalebarn
      data_template:
        message: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{"Oil Check: "+l}}
    - service: persistent_notification.create
      data_template:
        title: 'Oil Check'
        message: >
          {% set l = trigger.to_state.attributes.message.split(": ")|last %}
          {{"Oil Day: "+l}}
        notification_id: 'oil-check'

