- alias: "Table Tennis"
  trigger:
    - platform: state
      entity_id: switch.table_tennis
      to: "on"
  action:
    - service: script.table_tennis

- alias: "Party Mode"
  trigger:
    - platform: state
      entity_id: switch.party_mode
      to: "on"
  action:
    - service: script.party_mode
