# Heating On Demand
#
- alias: "Main Boiler Demand On"
  trigger:
    platform: state
    entity_id: group.main_heating_demand
    to: 'on'
    for:
      seconds: 10
  action:
    - service: switch.turn_on
      entity_id: switch.main_heating_relay_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.main_heating_thermostat_heating_1
        temperature: 22
    - service: notify.automations
      data:
        message: "Main Heating Demand on"


- alias: "Main Boiler Demand Off"
  trigger:
    platform: state
    entity_id: group.main_heating_demand
    to: 'off'
    for:
      seconds: 10
  action:
    - service: switch.turn_off
      entity_id: switch.main_heating_relay_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.main_heating_thermostat_heating_1
        temperature: 10
    - service: notify.automations
      data:
        message: "Main Heating Demand off"

- alias: "Annex Thermostat Demand On"
  trigger:
    - platform: state
      entity_id: group.annex_heating_demand
      to: 'on'
      for:
        seconds: 10
  action:
    - service: switch.turn_on
      entity_id: switch.horstmann_asrzw_thermostat_receiver_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.annex_heating_thermostat_heating_1
        temperature: 22
    - service: notify.automations
      data:
        message: "Annex Heating Demand on"

- alias: "Annex Thermostat Demand Off"
  trigger:
    - platform: state
      entity_id: group.annex_heating_demand
      to: 'off'
      for:
        seconds: 10
  action:
    - service: switch.turn_off
      entity_id: switch.horstmann_asrzw_thermostat_receiver_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.annex_heating_thermostat_heating_1
        temperature: 10
    - service: notify.automations
      data:
        message: "Annex Heating Demand off"

# Map virtual setpoint to real setpoint
- alias: "Set Real Thermostat"
  trigger:
    - platform: state
      entity_id: climate.lounge_east_thermostat
    - platform: state
      entity_id: climate.kitchen_thermostat
    - platform: state
      entity_id: climate.ballroom_east_thermostat
    - platform: state
      entity_id: climate.library_thermostat
    - platform: state
      entity_id: climate.annex_hall_thermostat
    - platform: state
      entity_id: climate.bedroom_ros_thermostat
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: '{{trigger.entity_id.replace("_thermostat", "_comfort_setpoint")}}'
        temperature: '{{ trigger.to_state.attributes.temperature }}'

# Map real setpoint to virtual setpoint
#- alias: "Set Virtual Thermostat"
#  trigger:
#    - platform: state
#      entity_id: climate.study_west_comfort_setpoint
#    - platform: state
#      entity_id: climate.study_east_comfort_setpoint
#    - platform: state
#      entity_id: climate.lounge_east_comfort_setpoint
#    - platform: state
#      entity_id: climate.bedroom_mark_north_comfort_setpoint
#    - platform: state
#      entity_id: climate.bedroom_mark_south_comfort_setpoint
#    - platform: state
#      entity_id: climate.kitchen_comfort_setpoint
#    - platform: state
#      entity_id: climate.ballroom_east_comfort_setpoint
#    - platform: state
#      entity_id: climate.library_comfort_setpoint
#    - platform: state
#      entity_id: climate.hall_west_comfort_setpoint
#    - platform: state
#      entity_id: climate.hall_east_comfort_setpoint
#    - platform: state
#      entity_id: climate.annex_hall_comfort_setpoint
#    - platform: state
#      entity_id: climate.bedroom_ros_comfort_setpoint
#  action:
#    #- service: climate.set_temperature
#    #  data_template:
#    #    entity_id: '{{trigger.entity_id.replace("_comfort_setpoint","_thermostat")}}'
#    #    temperature: '{{ trigger.to_state.attributes.temperature }}'
#    - service: notify.automations
#      data:
#        message: "Set Virtual Thermostat disabled"

# Tado temperature determines demand switch
- alias: "J's Bedroom Triggers Boiler"
  trigger:
    platform: state
    entity_id: climate.js_bedroom
  #condition:
  #  condition: state
  #  entity_id: sensor.js_bedroom_power
  #  state: 'ON'
  action:
    - service_template: >
        {% if trigger.to_state.attributes.current_temperature > (trigger.to_state.attributes.temperature + 1.0) %}
        switch.turn_off
        {% elif trigger.to_state.attributes.current_temperature < (trigger.to_state.attributes.temperature - 1.0) %}
        switch.turn_on
        {% endif %}
      entity_id: switch.js_bedroom_demand
