# Heating On Demand
#
- alias: main_boiler_demand_on
  trigger:
    platform: state
    entity_id: group.main_heating_demand
    to: 'on'
    for:
      seconds: 10
  action:
    - service: automation.trigger
      data:
        entity_id: automation.main_heating_poll_on
    - service: notify.automations
      data:
        message: "Main Heating Demand on"

- alias: main_heating_poll_on
  trigger:
    - platform: time_pattern
      minutes: '/20'
      seconds: 12
  condition:
    - condition: state
      entity_id: group.main_heating_demand
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.main_heating_relay_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.main_heating_thermostat_heating_1
        temperature: 22
        hvac_mode: 'heat'


- alias: main_boiler_demand_off
  trigger:
    platform: state
    entity_id: group.main_heating_demand
    to: 'off'
    for:
      seconds: 10
  action:
    - service: automation.trigger
      data:
        entity_id: automation.main_heating_poll_off
    - service: notify.automations
      data:
        message: "Main Heating Demand off"

- alias: main_heating_poll_off
  trigger:
    - platform: time_pattern
      minutes: '/20'
      seconds: 12
  condition:
    - condition: state
      entity_id: group.main_heating_demand
      state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.main_heating_relay_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.main_heating_thermostat_heating_1
        temperature: 10

- alias: annex_thermostat_demand_on
  trigger:
    - platform: state
      entity_id: group.annex_heating_demand
      to: 'on'
      for:
        seconds: 10
  action:
    - service: switch.turn_on
      entity_id: switch.annex_heating_relay_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.annex_heating_thermostat_heating_1
        temperature: 22
        hvac_mode: 'heat'
    - service: notify.automations
      data:
        message: "Annex Heating Demand on"

- alias: annex_thermostat_demand_off
  trigger:
    - platform: state
      entity_id: group.annex_heating_demand
      to: 'off'
      for:
        seconds: 10
  action:
    - service: switch.turn_off
      entity_id: switch.annex_heating_relay_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.annex_heating_thermostat_heating_1
        temperature: 10
    - service: notify.automations
      data:
        message: "Annex Heating Demand off"

# Map virtual setpoint to real setpoint
- alias: "Set Real Thermostat"
  trigger:
    # - platform: state
    #  entity_id: climate.xxx_thermostat
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: '{{trigger.entity_id.replace("_thermostat", "_mode")}}'
        temperature: '{{ trigger.to_state.attributes.temperature }}'

# Map real setpoint to virtual setpoint
#- alias: "Set Virtual Thermostat"
#  trigger:
#    - platform: state
#      entity_id: climate.study_west_mode
#    - platform: state
#      entity_id: climate.study_east_mode
#    - platform: state
#      entity_id: climate.lounge_east_mode
#    - platform: state
#      entity_id: climate.bedroom_mark_north_mode
#    - platform: state
#      entity_id: climate.bedroom_mark_south_mode
#    - platform: state
#      entity_id: climate.kitchen_mode
#    - platform: state
#      entity_id: climate.ballroom_east_mode
#    - platform: state
#      entity_id: climate.library_mode
#    - platform: state
#      entity_id: climate.hall_west_mode
#    - platform: state
#      entity_id: climate.hall_east_mode
#    - platform: state
#      entity_id: climate.annex_hall_mode
#    - platform: state
#      entity_id: climate.bedroom_annex2_mode
#    - platform: state
#      entity_id: climate.guest_room_heat
#  action:
#    #- service: climate.set_temperature
#    #  data_template:
#    #    entity_id: '{{trigger.entity_id.replace("_mode","_thermostat")}}'
#    #    temperature: '{{ trigger.to_state.attributes.temperature }}'
#    - service: notify.automations
#      data:
#        message: "Set Virtual Thermostat disabled"

