# Map virtual setpoint climate.foo_thermostat to setpoints group.g_foo_thermostat
- alias: heating_on_demand_set_real_thermostats
  trigger:
    - platform: state
      entity_id: climate.study_thermostat
    - platform: state
      entity_id: climate.kitchen_thermostat
    - platform: state
      entity_id: climate.hall_thermostat
    - platform: state
      entity_id: climate.annex_hall_thermostat
    - platform: state
      entity_id: climate.lounge_thermostat
    - platform: state
      entity_id: climate.library_thermostat
    - platform: state
      entity_id: climate.ballroom_thermostat
    - platform: state
      entity_id: climate.bedroom_mark_thermostat
    - platform: state
      entity_id: climate.bedroom_ros_thermostat
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: '{{trigger.entity_id.replace("climate.", "group.g_")}}'
        temperature: '{{ trigger.to_state.attributes.temperature }}'
