# Heating On Demand
#
- alias: "Main Boiler Demand On"
  trigger:
    platform: state
    entity_id: group.main_heating_demand
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.horstmann_unknown_type0003_id0002_switch_36_0
    - service: climate.set_temperature
      data:
        entity_id: climate.horstmann_scsc17_thermostat_heating_1_35_1
        temperature: 22

- alias: "Main Boiler Demand Off"
  trigger:
    platform: state
    entity_id: group.main_heating_demand
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.horstmann_unknown_type0003_id0002_switch_36_0
    - service: climate.set_temperature
      data:
        entity_id: climate.horstmann_scsc17_thermostat_heating_1_35_1
        temperature: 15

- alias: "Annex Thermostat Demand On"
  trigger:
    - platform: state
      entity_id: group.annex_heating_demand
      to: 'on'
  action:
    #- service: switch.turn_on
    #  entity_id: switch.horstmann_unknown_type0003_id0002_switch_36_0
    - service: climate.set_temperature
      data:
        entity_id: climate.horstmann_scsc17_thermostat_heating_1_50_1
        temperature: 22

- alias: "Annex Thermostat Demand Off"
  trigger:
    - platform: state
      entity_id: group.annex_heating_demand
      to: 'off'
  action:
    #- service: switch.turn_off
    #  entity_id: switch.horstmann_unknown_type0003_id0002_switch_36_0
    - service: climate.set_temperature
      data:
        entity_id: climate.horstmann_scsc17_thermostat_heating_1_50_1
        temperature: 15

# Map virtual setpoint to real setpoint
- alias: "Set Real Thermostat"
  trigger:
    - platform: state
      entity_id: climate.study_west_thermostat_15_1
    - platform: state
      entity_id: climate.study_east_thermostat_14_1
    - platform: state
      entity_id: climate.lounge_east_thermostat_30_1
    - platform: state
      entity_id: climate.bedroom_mark_thermostat_29_1
    - platform: state
      entity_id: climate.kitchen_thermostat_34_1
    - platform: state
      entity_id: climate.ballroom_east_thermostat_33_1
    - platform: state
      entity_id: climate.library_thermostat_25_1
    - platform: state
      entity_id: climate.hall_west_thermostat_13_1
    - platform: state
      entity_id: climate.hall_east_thermostat_24_1
    - platform: state
      entity_id: climate.annex_hall_thermostat_43_1
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: '{{trigger.entity_id.replace("thermostat_", "comfort_setpoint_")}}'
        temperature: '{{ trigger.to_state.attributes.temperature }}'


# Map real setpoint to virtual setpoint
- alias: "Set Virtual Thermostat"
  trigger:
    - platform: state
      entity_id: climate.study_west_comfort_setpoint_15_1
    - platform: state
      entity_id: climate.study_east_comfort_setpoint_14_1
    - platform: state
      entity_id: climate.lounge_east_comfort_setpoint_30_1
    - platform: state
      entity_id: climate.bedroom_mark_comfort_setpoint_29_1
    - platform: state
      entity_id: climate.kitchen_comfort_setpoint_34_1
    - platform: state
      entity_id: climate.ballroom_east_comfort_setpoint_33_1
    - platform: state
      entity_id: climate.library_comfort_setpoint_25_1
    - platform: state
      entity_id: climate.hall_west_comfort_setpoint_13_1
    - platform: state
      entity_id: climate.hall_east_comfort_setpoint_24_1
    - platform: state
      entity_id: climate.annex_hall_comfort_setpoint_43_1
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: '{{trigger.entity_id.replace("comfort_setpoint_","thermostat_")}}'
        temperature: '{{ trigger.to_state.attributes.temperature }}'

