# Hot Water
#   Weekdays: On at 5am, off at noon, on at 4pm, off at 11pm
#   Weekend: On at 5am, (on at 4pm,) off at 11pm
#
# Repeat the command every 20 minutes to avoid failsafe mode.
- alias: "Hot Water Off"
  trigger:
    - platform: time
      minutes: '/20'
      seconds: 10
  condition:
    condition: or
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
        after: '12:00:00'
        before: '16:00:00'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
        after: '23:00:00'
        before: '05:00:00'
      - condition: time
        weekday:
          - sat
          - sun
        after: '23:00:00'
        before: '05:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.horstmann_unknown_type0003_id0002_switch_36_0_3

- alias: "Hot Water On"
  trigger:
    - platform: time
      minutes: '/20'
      seconds: 5
  condition:
    condition: or
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
        after: '05:00:00'
        before: '12:00:00'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
        after: '16:00:00'
        before: '23:00:00'
      - condition: time
        weekday:
          - sat
          - sun
        after: '05:00:00'
        before: '23:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.horstmann_unknown_type0003_id0002_switch_36_0_3

- alias: "Hot Water Notify"
  trigger:
    - platform: state
      entity_id: switch.horstmann_unknown_type0003_id0002_switch_36_0_3
  action:
    - service: notify.automations
      data_template:
        message: 'Hot Water is now {{ trigger.to_state.state }}'
