# Hot Water
#   Weekdays: On at 5am, off at noon, on at 4pm, off at 11pm
#   Weekend: On at 5am, (on at 4pm,) off at 11pm
#
# Repeat the command every 20 minutes to avoid failsafe mode.
- alias: hot_water_off
  trigger:
    - platform: time_pattern
      minutes: '/20'
      seconds: 10
  condition:
    condition: or
    conditions:
      - condition: time
        after: '08:30:00'
        before: '16:00:00'
      - condition: time
        after: '17:00:00'
        before: '19:30:00'
      - condition: time
        after: '20:30:00'
        before: '06:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.main_heating_relay_instance_2_switch

- alias: hot_water_on
  trigger:
    - platform: time_pattern
      minutes: '/20'
      seconds: 5
  condition:
    condition: or
    conditions:
      - condition: time
        after: '06:30:00'
        before: '08:30:00'
      - condition: time
        after: '16:00:00'
        before: '17:00:00'
      - condition: time
        after: '19:30:00'
        before: '20:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.main_heating_relay_instance_2_switch

- alias: hot_water_notify
  trigger:
    - platform: state
      entity_id: switch.main_heating_relay_instance_2_switch
  action:
    - service: notify.automations
      data_template:
        message: 'Hot Water is now {{ trigger.to_state.state }}'
