- alias: "Ballroom Mood"
  trigger:
    platform: state
    entity_id: input_select.ballroom_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.ballroom_select", "Off") %}
            scene.ballroom_off
          {%-elif is_state("input_select.ballroom_select", "Party") %}
            scene.ballroom_party
          {%-elif is_state("input_select.ballroom_select", "Movie") %}
            scene.ballroom_movie
          {%-elif is_state("input_select.ballroom_select", "Bright") %}
            scene.ballroom_bright
          {% else %}
            None
          {% endif %}

- alias: "Mark's Bedroom Mood"
  trigger:
    platform: state
    entity_id: input_select.marks_bedroom_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.marks_bedroom_select", "Off") %}
            scene.marks_bedroom_off
          {%-elif is_state("input_select.marks_bedroom_select", "Sleep") %}
            scene.marks_bedroom_sleep
          {%-elif is_state("input_select.marks_bedroom_select", "Play") %}
            scene.marks_bedroom_play
          {% else %}
            None
          {% endif %}

- alias: "Library Mood"
  trigger:
    platform: state
    entity_id: input_select.library_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.library_select", "Off") %}
            scene.library_off
          {%-elif is_state("input_select.library_select", "Chat") %}
            scene.library_chat
          {%-elif is_state("input_select.library_select", "Read") %}
            scene.library_read
          {% else %}
            None
          {% endif %}

- alias: "Lounge Mood"
  trigger:
    platform: state
    entity_id: input_select.lounge_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.lounge_select", "Off") %}
            scene.lounge_off
          {%-elif is_state("input_select.lounge_select", "Cosy") %}
            scene.lounge_cosy
          {%-elif is_state("input_select.lounge_select", "Movie") %}
            scene.lounge_movie
          {%-elif is_state("input_select.lounge_select", "Bright") %}
            scene.lounge_bright
          {% else %}
            None
          {% endif %}

- alias: "Study Mood"
  trigger:
    platform: state
    entity_id: input_select.study_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.study_select", "Off") %}
            scene.study_off
          {%-elif is_state("input_select.study_select", "Work") %}
            scene.study_work
          {%-elif is_state("input_select.study_select", "Relax") %}
            scene.study_relax
          {% else %}
            None
          {% endif %}

- alias: "Guest Room Mood"
  trigger:
    platform: state
    entity_id: input_select.guest_room_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.guest_room_select", "Off") %}
            scene.guest_room_off
          {%-elif is_state("input_select.guest_room_select", "Sleep") %}
            scene.guest_room_sleep
          {%-elif is_state("input_select.guest_room_select", "Cosy") %}
            scene.guest_room_cosy
          {% else %}
            None
          {% endif %}

- alias: "Jerome's Bedroom Mood"
  trigger:
    platform: state
    entity_id: input_select.bedroom_jerome_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.bedroom_jerome_select", "Off") %}
            scene.bedroom_jerome_off
          {%-elif is_state("input_select.bedroom_jerome_select", "Sleep") %}
            scene.bedroom_jerome_sleep
          {%-elif is_state("input_select.bedroom_jerome_select", "Cosy") %}
            scene.bedroom_jerome_cosy
          {% else %}
            None
          {% endif %}

- alias: "Ros's Bedroom Mood"
  trigger:
    platform: state
    entity_id: input_select.bedroom_ros_select
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.bedroom_ros_select", "Off") %}
            scene.bedroom_ros_off
          {%-elif is_state("input_select.bedroom_ros_select", "Sleep") %}
            scene.bedroom_ros_sleep
          {%-elif is_state("input_select.bedroom_ros_select", "Cosy") %}
            scene.bedroom_ros_cosy
          {% else %}
            None
          {% endif %}
