alias: "Ballroom Mood"
trigger:
  platform: state
  entity_id: input_select.ballroom_select
action:
  - service: scene.turn_on
    data_template:
      entity_id: >
        {% if is_state("input_select.ballroom_select", "Off") %}
          scene.ballroom_off
        {%-elif is_state("input_select.ballroom_select", "Party") %}
          scene.ballroom_party
        {%-elif is_state("input_select.ballroom_select", "Movie") %}
          scene.ballroom_movie
        {%-elif is_state("input_select.ballroom_select", "Bright") %}
          scene.ballroom_bright
        {% else %}
          none
        {% endif %}
