#  All Off at 11pm weekdays, 3am weekend
- alias: reset_modes
  trigger:
    - platform: time
      at: '00:30:00'
    - platform: time
      at: '03:00:00'
  condition:
    condition: or
    conditions:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        after: '00:30:00'
      - condition: time
        weekday:
        - sat
        - sun
        after: '03:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.study_mode
        option: "Off"
    - service: input_select.select_option
      data:
        entity_id: input_select.kitchen_mode
        option: "Off"
    - service: input_select.select_option
      data:
        entity_id: input_select.lounge_mode
        option: "Off"
    - service: input_select.select_option
      data:
        entity_id: input_select.library_mode
        option: "Off"
    - service: input_select.select_option
      data:
        entity_id: input_select.ballroom_mode
        option: "Off"
