- alias: Stream Radio None
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: None
    - platform: state
      entity_id: input_select.kitchen_stream
      to: None
    - platform: state
      entity_id: input_select.lounge_stream
      to: None
    - platform: state
      entity_id: input_select.library_stream
      to: None
    - platform: state
      entity_id: input_select.ballroom_stream
      to: None
    - platform: state
      entity_id: input_select.marks_bedroom_stream
      to: None
  action:
    - service: media_player.stop
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}

- alias: Stream Radio 1
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.kitchen_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.lounge_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.library_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.ballroom_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.marks_bedroom_stream
      to: "Stream 1"
  action:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}
        media_content_id: >
          {% if is_state("input_select.radio_stream_1", "Absolute 60s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute60s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 70s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute70s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 80s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 90s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute90s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 00s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute00s.mp3
          {% else %}
            None
          {% endif %}
        media_content_type: 'audio/mp3'

- alias: Stream Radio 2
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.kitchen_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.lounge_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.library_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.ballroom_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.marks_bedroom_stream
      to: "Stream 2"
  action:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}
        media_content_id: >
          {% if is_state("input_select.radio_stream_1", "Absolute 60s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute60s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 70s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute70s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 80s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 90s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute90s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 00s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute00s.mp3
          {% else %}
            None
          {% endif %}
        media_content_type: 'audio/mp3'

- alias: Stream Radio 3
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.kitchen_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.lounge_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.library_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.ballroom_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.marks_bedroom_stream
      to: "Stream 3"
  action:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}
        media_content_id: >
          {% if is_state("input_select.radio_stream_1", "Absolute 60s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute60s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 70s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute70s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 80s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 90s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute90s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 00s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute00s.mp3
          {% else %}
            None
          {% endif %}
        media_content_type: 'audio/mp3'
