alias: Stream Radio none
trigger:
  - platform: state
    entity_id: input_select.study_stream
    state:  none
  - platform: state
    entity_id: input_select.kitchen_stream
    state:  none
  - platform: state
    entity_id: input_select.lounge_stream
    state:  none
  - platform: state
    entity_id: input_select.library_stream
    state:  none
  - platform: state
    entity_id: input_select.ballroom_stream
    state:  none
  - platform: state
    entity_id: input_select.marks_bedroom_stream
    state:  none
action:
  - service: media_player.stop
    data_template:
      entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}
