# Power detection for the washing machine.
# Debounce numeric_state with an input_boolean.
#
# Cycle determined empirically from event data
#
- alias: 'Washing Machine Hi'
  trigger:
    platform: numeric_state
    entity_id: sensor.greenwave_powernode_54_power
    above: 30
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.washing_machine_debouncer

- alias: 'Washing Machine Lo'
  trigger:
    platform: numeric_state
    entity_id: sensor.greenwave_powernode_54_power
    below: 20
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.washing_machine_debouncer

- alias: 'Washing Machine Started'
  trigger:
    platform: state
    entity_id: input_boolean.washing_machine_debouncer
    to: 'on'
    for:
      seconds: 120
  condition:
    - condition: state
      entity_id: binary_sensor.washing_machine
      state: 'off'
  action:
    # turn on binary_sensor.washing_machine
    - service: mqtt.publish
      data_template:
        topic: 'ha/event/washing-machine'
        payload: 'on'
    - service: notify.whalebarn
      data_template:
        message: 'Washing machine cycle started'


- alias: 'Washing Machine Stopped'
  trigger:
    platform: state
    entity_id: input_boolean.washing_machine_debouncer
    to: 'off'
    for:
      seconds: 300
  condition:
    - condition: state
      entity_id: binary_sensor.washing_machine
      state: 'on'
  action:
    # turn off binary_sensor.washing_machine
    - service: mqtt.publish
      data_template:
        topic: 'ha/event/washing-machine'
        payload: 'off'
    - service: notify.whalebarn
      data_template:
        message: 'Washing machine cycle ended'
    - service: persistent_notification.create
      data_template:
        title: 'Washing Machine'
        message: 'Washing cycle ended {{ as_timestamp(now()) | timestamp_custom("at %R on %a %d %b") }}'
        notification_id: 'washing-machine'
