homeassistant:
  customize:
    climate.lounge_thermostat:
      friendly_name: "Lounge Heating"
    sensor.lounge_temperature:
      friendly_name: "Lounge"
      icon: mdi:thermometer
      unit_of_measurement: "\xB0C"

group:
  g_debug_lounge_heating:
    entities:
      - climate.lounge_thermostat
      - climate.lounge_east_mode
      - switch.lounge_demand

  g_debug_lounge_temperature:
    entities:
      - sensor.lounge_temperature
      - sensor.lounge_east_current_temperature
      - sensor.lounge_east_temperature

  # Non-UI group which forwards setpoint updates
  #  Name is mapped from climate.foo_thermostat -> group.g_foo_thermostat
  g_lounge_thermostat:
    entities:
      - climate.lounge_east_mode

climate:
  - name: lounge_thermostat
    platform: generic_thermostat
    heater: switch.lounge_demand
    target_sensor: sensor.lounge_temperature
    max_temp: 25
    min_temp: 5
    target_temp: 10.0

switch:
  - name: lounge_demand
    platform: mqtt
    command_topic: ha/lounge/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

sensor:
  - name: lounge_east_current_temperature
    platform: mqtt
    state_topic: 'ha/raw/sensor.lounge_east_temperature/state'
    ## dev: for mock mqtt devices
    #value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: lounge_temperature
    platform: min_max
    type: max  # minimize occasional 0 readings. Replace with median?
    entity_ids:
      - sensor.lounge_east_current_temperature

  - platform: template
    sensors:
      lounge_setpoint:
        value_template: "{{ states.climate.lounge_thermostat.attributes.temperature }}"
        unit_of_measurement: "\xB0C"

automation:
  # Redirect received temperatures over mqtt
  - alias: "lounge_update_temperature"
    trigger:
      - platform: state
        entity_id: sensor.lounge_east_temperature
    action:
      - service: mqtt.publish
        data_template:
          topic: 'ha/raw/{{trigger.entity_id}}/state'
          payload: '{{ trigger.to_state.state }}'

