#
# Lounge
#

homeassistant:
  customize:
    group.lounge_lights:
      icon: mdi:lightbulb-on

    sensor.lounge_east_air_temperature:
      friendly_name: Lounge East

    climate.lounge_east_mode:
      min_temp: 5
      max_temp: 25

group:
  # floorplan
  lounge_compact_ui:
    name: Lounge
    icon: mdi:sofa
    entities:
    - input_select.lounge_mode
    - climate.lounge_thermostat
    - group.lounge_lights

  lounge_setpoints:
    name: Lounge Setpoints
    entities:
    - climate.lounge_east_mode

  lounge_lights:
    entities:
    - light.lounge_east
    - light.lounge_north
    - light.lounge_west
    name: Lounge Lights

scene:
  - name: lounge_off
    entities:
      group.lounge_lights:
        state: off
      media_player.lounge:
        state: paused
      media_player.snapcast_client_lounge:
        state: on
        is_volume_muted: true

  - name: lounge_cosy
    entities:
      group.lounge_lights:
        state: on
        brightness_pct: 20

  - name: lounge_bright
    entities:
      group.lounge_lights:
        state: on
        brightness_pct: 100

  - name: lounge_movie
    entities:
      group.lounge_lights:
        state: on
        brightness_pct: 50

switch:
  - name: Lounge East Demand
    platform: mqtt
    command_topic: ha/lounge/east/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

media_player:
  - name: lounge
    platform: kodi
    host: lounge
    port: 80

#script: !include_dir_merge_named scripts
#automation: !include_dir_merge_list automations
