#
# Lounge
#

homeassistant:
  customize:
    group.lounge_lights:
      icon: mdi:lightbulb-on

    climate.lounge_east_mode:
      min_temp: 5
      max_temp: 25

group:
  # floorplan
  lounge_compact_ui:
    name: Lounge
    icon: mdi:sofa
    entities:
      - input_select.lounge_mode
      - climate.lounge_thermostat
      - group.lounge_lights
      - media_player.lounge_multizone_audio

  lounge_setpoints:
    name: Lounge Setpoints
    entities:
      - climate.lounge_east_mode

  lounge_lights:
    entities:
      - light.lounge_east
      - light.lounge_north
      - light.lounge_west
    name: Lounge Lights

scene:
  - name: lounge_off
    entities:
      group.lounge_lights:
        state: off
      media_player.lounge_multizone_audio:
        state: paused

  - name: lounge_cosy
    entities:
      group.lounge_lights:
        state: on
        brightness_pct: 20

  - name: lounge_bright
    entities:
      group.lounge_lights:
        state: on
        brightness_pct: 100

  - name: lounge_movie
    entities:
      group.lounge_lights:
        state: on
        brightness_pct: 50

switch:
  - name: Lounge East Demand
    platform: mqtt
    command_topic: ha/lounge/east/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

#script: !include_dir_merge_named scripts
#automation: !include_dir_merge_list automations
