group:
  g_lounge_settings_ui:
    name: Settings
    icon: mdi:settings
    entities:
      - input_number.lounge_temperature_off
      - input_number.lounge_temperature_cosy
      - input_number.lounge_temperature_bright
      - input_number.lounge_temperature_movie
