group:
  g_bedroom_ros_settings_ui:
    name: Settings
    icon: mdi:settings
    control: hidden
    entities:
      - input_number.bedroom_ros_temperature_off
      - input_number.bedroom_ros_temperature_sleep
      - input_number.bedroom_ros_temperature_cosy


