#
# Dim lights based on media player status
#

group:
  g_bedroom_mark_media_dimming:
    name: Media Auto Dim
    control: hidden
    entities:
      - input_boolean.bedroom_mark_dim_for_movie
      - input_boolean.bedroom_mark_dim_for_tv
      - input_slider.bedroom_mark_media_dimmer_level

input_boolean:
  bedroom_mark_dim_for_tv:
    name: Dim during TV shows
  bedroom_mark_dim_for_movie:
    name: Dim during Movies

input_slider:
  bedroom_mark_media_dimmer_level:
    name: 'Dim Level'
    min: 0
    max: 40
    step: 5

automation:
- alias: "Bedroom Mark Dim on Media Playing"
  trigger:
    - platform: state
      entity_id: media_player.marks_bedroom
      to: 'playing'
      for:
        seconds: 2

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: group.marks_bedroom_lights
        state: 'on'
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.bedroom_mark_dim_for_movie
            state: 'on'
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.media_content_type == "movie" }}
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.bedroom_mark_dim_for_tv
            state: 'on'
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.media_content_type == "tvshow" }}

  action:
    service: light.turn_on
    data_template:
      entity_id: group.marks_bedroom_lights
      brightness_pct: '{{ states.input_slider.bedroom_mark_media_dimmer_level.state | int }}'
      transition: '2'


- alias: "Bedroom Mark Dim on Media Paused"
  trigger:
    - platform: state
      entity_id: media_player.marks_bedroom
      to: 'paused'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: group.marks_bedroom_lights
        state: 'on'
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.bedroom_mark_dim_for_movie
            state: 'on'
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.media_content_type == "music" }}
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.bedroom_mark_dim_for_tv
            state: 'on'
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.media_content_type == "tvshow" }}

  action:
    service: light.turn_on
    data:
      entity_id: group.marks_bedroom_lights
      brightness_pct: '50'
      transition: '3'

- alias: "Bedroom Mark Dim on Media Stopped"
  trigger:
    - platform: state
      entity_id: media_player.marks_bedroom
      from: 'playing'
      to: 'idle'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: group.marks_bedroom_lights
        state: 'on'
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.bedroom_mark_dim_for_movie
            state: 'on'
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.media_content_type == "music" }}
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.bedroom_mark_dim_for_tv
            state: 'on'
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.media_content_type == "tvshow" }}

  action:
    service: scene.turn_on
    entity_id: scene.marks_bedroom_play

homeassistant:
  customize:
    group.g_bedroom_mark_media_dimming:
      icon: mdi:brightness-auto
    input_boolean.bedroom_mark_dim_for_movie:
      icon: mdi:movie
    input_boolean.bedroom_mark_dim_for_tv:
      icon: mdi:television-classic
    input_slider.bedroom_mark_media_dimmer_level:
      icon: mdi:brightness-6
