# Hot Tub UI entity (read-only)
#
# Triggered by automation.hottub_started
# and automation.hottub_stopped
#
binary_sensor:
- name: hottub
  platform: mqtt
  state_topic: ha/event/hottub
  payload_on: 'on'
  payload_off: 'off'
  initial: off

input_boolean:
  hottub_debouncer:
    name: "Hot Tub Debouncer"
    initial: off

homeassistant:
  customize:
    binary_sensor.hottub:
      friendly_name: Hot Tub Heating
      icon: mdi:pot
    switch.greenwave_powernode_53_switch:
      friendly_name: Hot Tub Power Supply
      icon: mdi:pot
      emulated_hue: true
    sensor.greenwave_powernode_53_energy:
      friendly_name: Hot Tub Energy
    sensor.greenwave_powernode_53_power:
      friendly_name: Hot Tub Power

group:
  g_hottub:
    name: Hot Tub
    icon: mdi:pot
    entities:
    - binary_sensor.hottub
    - switch.greenwave_powernode_53_switch
    - sensor.greenwave_powernode_53_energy
    - sensor.greenwave_powernode_53_power

# Power detection for the hot tub
# Debounce numeric_state with an input_boolean.
#
# Hot tub heater load is ~2000W
# Filter only load is ~30W
#
automation:
- alias: 'Hot Tub Hi'
  trigger:
    platform: numeric_state
    entity_id: sensor.greenwave_powernode_53_power
    above: 1500
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.hottub_debouncer

- alias: 'Hot Tub Lo'
  trigger:
    platform: numeric_state
    entity_id: sensor.greenwave_powernode_53_power
    below: 200
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.hottub_debouncer

- alias: 'Hot Tub Started'
  trigger:
    platform: state
    entity_id: input_boolean.hottub_debouncer
    to: 'on'
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: binary_sensor.hottub
      state: 'off'
  action:
    # turn on binary_sensor.hottub
    - service: mqtt.publish
      data_template:
        topic: 'ha/event/hottub'
        payload: 'on'
    - service: notify.automations
      data_template:
        message: 'Hot Tub heating started'


- alias: 'Hot Tub Stopped'
  trigger:
    platform: state
    entity_id: input_boolean.hottub_debouncer
    to: 'off'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.hottub
      state: 'on'
  action:
    # turn off binary_sensor.hottub
    - service: mqtt.publish
      data_template:
        topic: 'ha/event/hottub'
        payload: 'off'
    - service: notify.whalebarn
      data_template:
        message: 'Hot Tub heating finished'
    - service: persistent_notification.create
      data:
        title: 'Hot Tub'
        message: 'Heating stopped {{ as_timestamp(now()) | timestamp_custom("at %R on %a %d %b") }}'
        notification_id: 'hottub'
