#
# Dim lights based on media player status
#

group:
  g_lounge_media_dimming:
    name: Media Auto Dim
    control: hidden
    entities:
      - input_boolean.lounge_media_dimming_enable
      - input_slider.lounge_media_dimmer_level

input_boolean:
  lounge_media_dimming_enable:
    name: Enable

input_slider:
  lounge_media_dimmer_level:
    name: 'Dim Level'
    min: 0
    max: 40
    step: 5

automation:
- alias: "Lounge Dim on Media Playing"
  trigger:
    - platform: state
      entity_id: media_player.lounge
      to: 'playing'
      for:
        seconds: 2

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.lounge_media_dimming_enable
        state: 'on'
      - condition: state
        entity_id: group.lounge_lights
        state: 'on'

  action:
    service: light.turn_on
    data_template:
      entity_id: group.lounge_lights
      brightness_pct: '{{ states.input_slider.lounge_media_dimmer_level.state | int }}'
      transition: '2'


- alias: "Lounge Dim on Media Paused"
  trigger:
    - platform: state
      entity_id: media_player.lounge
      to: 'paused'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.lounge_media_dimming_enable
        state: 'on'
      - condition: state
        entity_id: group.lounge_lights
        state: 'on'

  action:
    service: light.turn_on
    data:
      entity_id: group.lounge_lights
      brightness_pct: '50'
      transition: '3'

- alias: "Lounge Dim on Media Stopped"
  trigger:
    - platform: state
      entity_id: media_player.lounge
      from: 'playing'
      to: 'idle'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.lounge_media_dimming_enable
        state: 'on'
      - condition: state
        entity_id: group.lounge_lights
        state: 'on'

  action:
    service: scene.turn_on
    entity_id: scene.lounge_bright

homeassistant:
  customize:
    group.g_lounge_media_dimming:
      icon: mdi:movie
    input_boolean.lounge_media_dimming_enable:
      icon: none
    input_slider.lounge_media_dimmer_level:
      icon: mdi:brightness-6
