homeassistant:
  customize:
    script.all_rooms_audio:
      friendly_name: Music Everywhere
      icon: mdi:music-box-outline
      emulated_hue: true
    media_player.mpd:
      friendly_name: "Iris Media Player"
      icon: mdi:speaker-wireless
    media_player.snapcast_client_study:
      friendly_name: Study Snapcast
    media_player.snapcast_client_kitchen2:
      friendly_name: Kitchen Snapcast
    media_player.snapcast_client_lounge:
      friendly_name: Lounge Snapcast
    media_player.snapcast_client_library:
      friendly_name: Library Snapcast
    media_player.snapcast_client_ballroom:
      friendly_name: Ballroom Snapcast
    media_player.snapcast_client_outside:
      friendly_name: Outside Snapcast
    media_player.snapcast_client_bedroommark:
      friendly_name: "Mark's Bedroom Snapcast"
    media_player.snapcast_client_9cb6d08b2a6f:
      friendly_name: Canard Snapcast

    input_number.snapcast_client_bedroommark:
      entity_picture: /local/wb-icons/wb_mark.png

input_number:
    snapcast_client_study:
      name: Study Volume
      icon: mdi:printer
      min: 0
      max: 100
    snapcast_client_kitchen2:
      name: Kitchen Volume
      icon: mdi:stove
      min: 0
      max: 100
    snapcast_client_lounge:
      name: Lounge Volume
      icon: mdi:sofa
      min: 0
      max: 100
    snapcast_client_library:
      name: Library Volume
      icon: mdi:library
      min: 0
      max: 100
    snapcast_client_ballroom:
      name: Ballroom Volume
      icon: mdi:projector
      min: 0
      max: 100
    snapcast_client_outside:
      name: Outside Volume
      icon: mdi:pine-tree
      min: 0
      max: 100
    snapcast_client_bedroommark:
      name: "Mark's Bedroom Volume"
      icon: mdi:account
      min: 0
      max: 100
    snapcast_client_9cb6d08b2a6f:
      name: Canard Volume
      icon: mdi:laptop-chromebook
      min: 0
      max: 100

automation:
- alias: update_media_player_volume
  trigger:
    platform: state
    entity_id:
      - input_number.snapcast_client_study
      - input_number.snapcast_client_kitchen2
      - input_number.snapcast_client_lounge
      - input_number.snapcast_client_library
      - input_number.snapcast_client_ballroom
      - input_number.snapcast_client_bedroommark
      - input_number.snapcast_client_outside
  action:
    # don't unmute by default
    #- service: media_player.volume_mute
    #  data_template:
    #    entity_id: '{{trigger.entity_id.replace("input_number", "media_player")}}'
    #    is_volume_muted: false
    - service: media_player.volume_set
      data_template:
        entity_id: '{{trigger.entity_id.replace("input_number", "media_player")}}'
        volume_level: '{{ trigger.to_state.state | float / 100 }}'

- alias: update_input_number_volume
  trigger:
    platform: state
    entity_id:
      - media_player.snapcast_client_study
      - media_player.snapcast_client_kitchen2
      - media_player.snapcast_client_lounge
      - media_player.snapcast_client_library
      - media_player.snapcast_client_ballroom
      - media_player.snapcast_client_bedroommark
      - media_player.snapcast_client_outside
  action:
    - service: input_number.set_value
      data_template:
        entity_id: '{{trigger.entity_id.replace("media_player", "input_number")}}'
        value: '{{ trigger.to_state.attributes.volume_level * 100 }}'


media_player:
  - platform: snapcast
    host: media

  - platform: mpd
    host: media
    location: Multi-Room Controller

group:
  g_multiroom_audio_ui:
    name: Multiroom Audio
    view: true
    icon: mdi:music
    entities:
      - media_player.mpd
      - group.snapclient_volumes
      - group.snapclients

  snapclients:
    name: Snapcast Clients
    entities:
    - media_player.snapcast_client_study
    - media_player.snapcast_client_kitchen2
    - media_player.snapcast_client_lounge
    - media_player.snapcast_client_library
    - media_player.snapcast_client_ballroom
    - media_player.snapcast_client_bedroommark
    - media_player.snapcast_client_outside

  snapclient_volumes:
    name: Snapcast Volume
    entities:
    - input_number.snapcast_client_study
    - input_number.snapcast_client_kitchen2
    - input_number.snapcast_client_lounge
    - input_number.snapcast_client_library
    - input_number.snapcast_client_ballroom
    - input_number.snapcast_client_bedroommark
    - input_number.snapcast_client_outside

#tts:
#  - platform: google
#    cache: true
#    cache_dir: /tmp/tts
#    time_memory: 300

script:
  all_rooms_audio:
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: group.media_players
      - service: media_player.volume_set
        data:
          entity_id: group.snapclients
          volume_level: 0.5
      - service: media_player.select_source
        data:
          entity_id: media_player.ballroom_amplifier
          source: 'Media'
      - service: media_player.select_source
        data:
          entity_id: media_player.outside_amplifier
          source: 'Media'


  tts_broadcast:
    sequence:
      - service: snapcast.snapcast_snapshot
        data:
          entity_id:
            - group.snapclients
      - service: media_player.select_source
        data:
          entity_id: group.snapclients
          source: TTS
      - service: media_player.volume_set
        data:
          entity_id: group.snapclients
          volume_level: 0.5
      - service_template: "tts.google_say"
        data_template:
          entity_id: media_player.tts
          message: "{{message}}"
      - wait_template: "{{states.media_player.tts.state == 'idle'}}"
        timeout: 120
      - service: snapcast.snapcast_restore
        data:
          entity_id:
            - group.snapclients
