group:
  g_oil_tanks:
    name: Oil Levels
    entities:
    - sensor.oil_main_litres
    - sensor.oil_main_percentage
    - sensor.oil_main_days_remaining
    - sensor.oil_annex_litres
    - sensor.oil_annex_percentage
    - sensor.oil_annex_days_remaining

sensor:
  - name: oil_main_litres
    platform: mqtt
    state_topic: ha/myolive/1905
    value_template: '{{ value_json.Litres }}'
    unit_of_measurement: 'L'

  - name: oil_main_percentage
    platform: mqtt
    state_topic: ha/myolive/1905
    value_template: '{{ value_json.Percentage }}'
    unit_of_measurement: '%'

  - name: oil_main_days_remaining
    platform: mqtt
    state_topic: ha/myolive/1905
    value_template: '{{ value_json.DaysRemaining }}'

  - name: oil_annex_litres
    platform: mqtt
    state_topic: ha/myolive/1916
    value_template: '{{ value_json.Litres }}'
    unit_of_measurement: 'L'

  - name: oil_annex_percentage
    platform: mqtt
    state_topic: ha/myolive/1916
    value_template: '{{ value_json.Percentage }}'
    unit_of_measurement: '%'

  - name: oil_annex_days_remaining
    platform: mqtt
    state_topic: ha/myolive/1916
    value_template: '{{ value_json.DaysRemaining }}'


homeassistant:
  customize:
    # No matching device classes, so set default icons here
    sensor.oil_main_litres:
      icon: mdi:oil-level
    sensor.oil_main_percentage:
      icon: mdi:water-percent
    sensor.oil_main_days_remaining:
      icon: mdi:timer-sand
    sensor.oil_annex_litres:
      icon: mdi:oil-level
    sensor.oil_annex_percentage:
      icon: mdi:water-percent
    sensor.oil_annex_days_remaining:
      icon: mdi:timer-sand
