# Streaming Radio with parallel streams to multiple rooms
#
# UI groups:
#  - radio
#  - radio_streams: select a radio station for each stream
#  - radio_stream_map: select a stream for each room
#
group:
  radio:
    name: Internet Radio
    icon: mdi:radio
    entities:
    - group.radio_streams
    - group.radio_stream_map

  radio_streams:
    name: Radio Channels
    entities:
    - input_select.radio_stream_1
    - input_select.radio_stream_2
    - input_select.radio_stream_3

  radio_stream_map:
    name: Player Streams
    entities:
    - input_select.study_stream
    - input_select.kitchen_stream
    - input_select.lounge_stream
    - input_select.library_stream
    - input_select.ballroom_stream
    - input_select.bedroom_mark_stream

automation:
- alias: Stream Radio None
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: None
    - platform: state
      entity_id: input_select.kitchen_stream
      to: None
    - platform: state
      entity_id: input_select.lounge_stream
      to: None
    - platform: state
      entity_id: input_select.library_stream
      to: None
    - platform: state
      entity_id: input_select.ballroom_stream
      to: None
    - platform: state
      entity_id: input_select.bedroom_mark_stream
      to: None
  action:
    - service: media_player.stop
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}

- alias: Stream Radio 1
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.kitchen_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.lounge_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.library_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.ballroom_stream
      to: "Stream 1"
    - platform: state
      entity_id: input_select.bedroom_mark_stream
      to: "Stream 1"
  action:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}
        media_content_id: >
          {% if is_state("input_select.radio_stream_1", "Absolute 60s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute60s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 70s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute70s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 80s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 90s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute90s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 00s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute00s.mp3
          {% else %}
            None
          {% endif %}
        media_content_type: 'audio/mp3'

- alias: Stream Radio 2
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.kitchen_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.lounge_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.library_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.ballroom_stream
      to: "Stream 2"
    - platform: state
      entity_id: input_select.bedroom_mark_stream
      to: "Stream 2"
  action:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}
        media_content_id: >
          {% if is_state("input_select.radio_stream_1", "Absolute 60s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute60s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 70s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute70s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 80s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 90s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute90s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 00s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute00s.mp3
          {% else %}
            None
          {% endif %}
        media_content_type: 'audio/mp3'

- alias: Stream Radio 3
  trigger:
    - platform: state
      entity_id: input_select.study_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.kitchen_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.lounge_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.library_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.ballroom_stream
      to: "Stream 3"
    - platform: state
      entity_id: input_select.bedroom_mark_stream
      to: "Stream 3"
  action:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.{{ trigger.entity_id.split('.')[1].split('_stream')[0] }}
        media_content_id: >
          {% if is_state("input_select.radio_stream_1", "Absolute 60s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute60s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 70s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute70s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 80s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 90s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute90s.mp3
          {%-elif is_state("input_select.radio_stream_1", "Absolute 00s") %}
            http://icy-e-bab-04-cr.sharp-stream.com/absolute00s.mp3
          {% else %}
            None
          {% endif %}
        media_content_type: 'audio/mp3'

input_select:
  radio_stream_1:
    name: Stream 1
    <<: &stream_defaults
      options:
        - None
        - "Absolute 80s"
        - "Absolute 60s"
        - "Absolute 70s"
        - "Absolute 90s"
        - "Absolute 00s"
      initial: None
      icon: mdi:radio

  radio_stream_2:
    name: Stream 2
    <<: *stream_defaults

  radio_stream_3:
    name: Stream 3
    <<: *stream_defaults

  study_stream:
    name: Study
    icon: mdi:printer
    <<: &room_stream_defaults
      initial: None
      options:
        - None
        - "Stream 1"
        - "Stream 2"
        - "Stream 3"

  kitchen_stream:
    name: Kitchen
    icon: mdi:stove
    <<: *room_stream_defaults

  lounge_stream:
    name: Lounge
    icon: mdi:sofa
    <<: *room_stream_defaults

  library_stream:
    name: Library
    icon: mdi:library
    <<: *room_stream_defaults

  ballroom_stream:
    name: Ballroom
    icon: mdi:projector
    <<: *room_stream_defaults

  bedroom_mark_stream:
    name: "Mark's Bedroom"
    icon: mdi:hotel
    <<: *room_stream_defaults
