homeassistant:
  customize:
    climate.bedroom_annex2_thermostat:
      friendly_name: "Annex Bedroom 2 Heating"
    sensor.bedroom_annex2_mean_temperature:
      icon: mdi:thermometer
      unit_of_measurement: "\xB0C"
    automation.bedroom_annex2_set_real_thermostats:
      friendly_name: Update Real Thermostats

group:
  g_debug_bedroom_annex2_heating:
    entities:
      - climate.bedroom_annex2_thermostat
      - climate.bedroom_annex2_west_thermostat
      - switch.bedroom_annex2_demand

  g_debug_bedroom_annex2_temperature:
    entities:
      - sensor.bedroom_annex2_mean_temperature
      - sensor.bedroom_annex2_current_temperature
      - sensor.bedroom_annex2_west_air_temperature

  # Non-UI group which forwards setpoint updates
  #  Name is mapped from climate.foo_thermostat -> group.g_foo_thermostat
  g_bedroom_annex2_thermostat:
    entities:
      - climate.bedroom_annex2_west_thermostat

climate:
  - name: bedroom_annex2_thermostat
    platform: generic_thermostat
    heater: switch.bedroom_annex2_demand
    target_sensor: sensor.bedroom_annex2_mean_temperature
    max_temp: 25
    min_temp: 8  # spirit-Z minimum
    target_temp: 10.0
    cold_tolerance: 0.5
    hot_tolerance: 0.0

switch:
  - name: bedroom_annex2_demand
    platform: mqtt
    command_topic: ha/bedroom-annex2/demand/command
    payload_off: 'OFF'
    payload_on: 'ON'
    retain: true

sensor:
  - name: bedroom_annex2_current_temperature
    platform: mqtt
    state_topic: 'ha/raw/sensor.bedroom_annex2_west_air_temperature/state'
    ## dev: for mock mqtt devices
    #value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "\xB0C"
    expire_after: 1800  # 30mins
    force_update: true

  - name: bedroom_annex2_mean_temperature
    platform: min_max
    type: max  # minimize occasional 0 readings. Replace with median?
    entity_ids:
      - sensor.bedroom_annex2_current_temperature

  - platform: template
    sensors:
      bedroom_annex2_setpoint:
        value_template: "{{ states.climate.bedroom_annex2_thermostat.attributes.temperature }}"
        unit_of_measurement: "\xB0C"


automation:
  # Redirect received temperatures over mqtt
  - alias: "bedroom_annex2_update_temperature"
    trigger:
      - platform: state
        entity_id: sensor.bedroom_annex2_west_air_temperature
    action:
      - service: mqtt.publish
        data_template:
          topic: 'ha/raw/{{trigger.entity_id}}/state'
          payload: '{{ trigger.to_state.state }}'

  # Sync all thermostats (real and virtual)
  - alias: "bedroom_annex2_update_setpoint"
    trigger:
      - platform: state
        entity_id: climate.bedroom_annex2_west_thermostat
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.bedroom_annex2_thermostat
          temperature: '{{ trigger.to_state.attributes.temperature }}'

  - alias: bedroom_annex2_set_real_thermostats
    trigger:
      - platform: state
        entity_id: climate.bedroom_annex2_thermostat
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: group.g_bedroom_annex2_thermostat
          temperature: '{{ trigger.to_state.attributes.temperature }}'
