#
# Mode selection
#
# Stores last user intent.
# Reverts to manual when user adjustments are made.
#

homeassistant:
  customize:
    input_select.bedroom_annex2_mode:
      icon: mdi:bed-empty

input_select:
  bedroom_annex2_mode:
    name: "Annex Bedroom 2 Mode"
    options:
      - 'Off'
      - 'Cosy'
      - 'Sleep'
      - 'Manual'
    initial: 'Off'

input_number:
  bedroom_annex2_temperature_off:
    name: 'Off Temp'
    initial: 10
    <<: &bedroom_annex2_temp_defaults
      icon: mdi:thermostat
      unit_of_measurement: "\xB0C"
      min: 5
      max: 25
      step: 1

  bedroom_annex2_temperature_cosy:
    name: 'Cosy Temp'
    initial: 20
    <<: *bedroom_annex2_temp_defaults

  bedroom_annex2_temperature_sleep:
    name: 'Sleep Temp'
    initial: 15
    <<: *bedroom_annex2_temp_defaults


automation:
  - alias: bedroom_annex2_revert_to_manual
    trigger:
      - platform: state
        entity_id:
          - group.bedroom_annex2_lights
          - sensor.bedroom_annex2_setpoint
    #condition:
    #  condition: template  # otherwise we reset on all state updates
    #  value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
        - service: input_select.select_option
          data:
            entity_id: input_select.bedroom_annex2_mode
            option: 'Manual'


  - alias: bedroom_annex2_mode
    trigger:
      - platform: state
        entity_id: input_select.bedroom_annex2_mode
    action:
      - service: script.set_mode
        data_template:
          room: 'bedroom_annex2'
          mode: '{{ trigger.to_state.state | lower }}'
