#
# Ros's Room
#

homeassistant:
  customize:
    climate.bedroom_annex2_west_thermostat:
      min_temp: 8
      max_temp: 25

group:
  # floorplan
  bedroom_annex2_compact_ui:
    name: "Lucas's Bedroom"
    entities:
      - input_select.bedroom_annex2_mode
      - climate.bedroom_annex2_thermostat
      - group.bedroom_annex2_lights

  bedroom_annex2_setpoints:
    entities:
      - climate.bedroom_annex2_west_thermostat

  bedroom_annex2_lights:


scene:
  - name: bedroom_annex2_off
    entities:
      group.bedroom_annex2_lights:
        state: off
      switch.bedroom_annex2_appliances:
        state: off

  - name: bedroom_annex2_sleep
    entities:
      group.bedroom_annex2_lights:
        state: off

  - name: bedroom_annex2_cosy
    entities:
      group.bedroom_annex2_lights:
        state: on

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
