#
# Ros's Room
#

homeassistant:
  customize:
    sensor.bedroom_annex2_battery_level:
      icon: mdi:battery
    climate.bedroom_annex2_west_mode:
      min_temp: 5
      max_temp: 25

group:
  # floorplan
  bedroom_annex2_compact_ui:
    name: "Monica's Bedroom"
    entities:
    - input_select.bedroom_annex2_mode
    - climate.bedroom_annex2_thermostat
    - group.bedroom_annex2_lights

  bedroom_annex2_setpoints:
    entities:
    - climate.bedroom_annex2_west_mode

  bedroom_annex2_lights:


scene:
  - name: bedroom_annex2_off
    entities:
      group.bedroom_annex2_lights:
        state: off
      switch.bedroom_annex2_appliances:
        state: off

  - name: bedroom_annex2_sleep
    entities:
      group.bedroom_annex2_lights:
        state: off

  - name: bedroom_annex2_cosy
    entities:
      group.bedroom_annex2_lights:
        state: on

#automation: !include_dir_merge_list automations
#script: !include_dir_merge_named scripts
