- platform: template
  sensors:
    bedroom_annex2_battery:
      value_template: >
        {% if states.zwave.bedroom_annex2 %}
          {{ states.zwave.bedroom_annex2.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
      entity_id: zwave.bedroom_annex2
