- alias: "Calendar Annex Bedroom 2 Scene"
  trigger:
    - platform: state
      entity_id: calendar.annex2_scene
      to: "on"
  action:
    - service_template: input_select.select_option
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "bedroom_annex2" in l or "annex2" in l or ("annex" in l and "bedroom2" in l) %}
          {%   set u = "bedroom_annex2" %}
          {% endif %}
          input_select.{{u}}_mode
        option: >
          {% set v = trigger.to_state.attributes.message.lower().split()|last %}
          {{ v[0].upper() ~ v[1:].lower() }}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/annex2-scene'
        payload: '{{trigger.to_state.attributes.message}}'

- alias: "Calendar Annex Bedroom 2 Climate"
  trigger:
    - platform: state
      entity_id: calendar.annex2_climate
      to: "on"
  action:
    - service_template: climate.set_temperature
      data_template:
        entity_id: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {% if "bedroom_annex2" in l or "annex2" in l or ("annex" in l and "bedroom2" in l) %}
          {%   set u = "bedroom_annex2" %}
          {% endif %}
          climate.{{u}}_thermostat
        temperature: >
          {% set l = trigger.to_state.attributes.message.lower().split() %}
          {{l|last|float}}
    - service: mqtt.publish
      data_template:
        topic: 'ha/calendar/annex2-climate'
        payload: '{{trigger.to_state.attributes.message}}'

